Y::DebugConsole
DebugConsole Y.DebugConsole._Instance
Referenced by Y.DebugConsole.Awake.
DebugConsole Y.DebugConsole.Instance
StringBuilder Y.DebugConsole.builder
Referenced by Y.DebugConsole.ColorizeText.
Text Y.DebugConsole.output
InputField Y.DebugConsole.input
Button Y.DebugConsole.enter
Referenced by Y.DebugConsole.Execute.
Button Y.DebugConsole.cancel
bool Y.DebugConsole.wasFocused
Referenced by Y.DebugConsole.Update.
bool Y.DebugConsole.cancelRequest
Referenced by Y.DebugConsole.Execute, Y.DebugConsole.OnCancel, Y.DebugConsole.OnEnable.
static void Y.DebugConsole.InitializeOnLoad()
static string Y.DebugConsole.Error(string text)
References Y.DebugConsole.ColorizeText.
Referenced by Y.Commands.Execute, Y.DebugConsole.OnSubmit.
static string Y.DebugConsole.Success(string text)
References Y.DebugConsole.ColorizeText.
static string Y.DebugConsole.Alias(string text)
References Y.DebugConsole.ColorizeText.
static string Y.DebugConsole.Warning(string text)
References Y.DebugConsole.ColorizeText.
static string Y.DebugConsole.ColorizeText(string text, Color?color=null, bool bold=false, bool italic=false)
References Y.DebugConsole.builder.
Referenced by Y.DebugConsole.Alias, Y.DebugConsole.Error, Y.DebugConsole.Hello, Y.DebugConsole.Success, Y.DebugConsole.Warning.
void Y.DebugConsole.Awake()
References Y.DebugConsole._Instance, Y.DebugConsole.OnCancel, Y.DebugConsole.OnSubmit.
void Y.DebugConsole.OnEnable()
References Y.DebugConsole.cancelRequest, Y.DebugConsole.Hello.
void Y.DebugConsole.Update()
References Y.DebugConsole.OnSubmit, Y.DebugConsole.wasFocused.
void Y.DebugConsole.OnCancel()
References Y.DebugConsole.cancelRequest.
Referenced by Y.DebugConsole.Awake.
IEnumerator Y.DebugConsole.Execute(string command)
References Y.DebugConsole.cancelRequest, Y.DebugConsole.enter, Y.DebugConsole.WriteLine.
Referenced by Y.DebugConsole.OnSubmit.
void Y.DebugConsole.WriteLine(string command)
Referenced by Y.DebugConsole.Execute, Y.DebugConsole.Hello, Y.DebugConsole.OnSubmit.
void Y.DebugConsole.Hello()
References Y.DebugConsole.ColorizeText, Y.DebugConsole.WriteLine.
Referenced by Y.DebugConsole.OnEnable.
void Y.DebugConsole.OnSubmit()
Referenced by Y.DebugConsole.Awake, Y.DebugConsole.Update.
void Y.DebugConsole.OnSubmit(string command)
References Y.DebugConsole.Error, Y.DebugConsole.Execute, Y.DebugConsole.WriteLine.