Y::DebugPanelView
DebugPanelView Y.DebugPanelView.instance
Referenced by Y.DebugPanelView.CreateBerryPanel, Y.DebugPanelView.OnEnable.
float Y.DebugPanelView.messageHeight
Referenced by Y.DebugPanelView.GetMessageRect, Y.DebugPanelView.InitializeStyles.
GUIStyle Y.DebugPanelView.messageNameStyle
Referenced by Y.DebugPanelView.DrawDelegateMessage, Y.DebugPanelView.DrawMessage, Y.DebugPanelView.InitializeStyles.
GUIStyle Y.DebugPanelView.messageValueStyle
Referenced by Y.DebugPanelView.DrawMessage, Y.DebugPanelView.InitializeStyles.
GUIStyle Y.DebugPanelView.categoryStyle
Referenced by Y.DebugPanelView.DrawDelegateMessage, Y.DebugPanelView.DrawLog, Y.DebugPanelView.InitializeStyles.
GUIStyle Y.DebugPanelView.outputBackgroundStyle
Referenced by Y.DebugPanelView.DrawLog, Y.DebugPanelView.InitializeStyles.
Texture2D Y.DebugPanelView.blackTexture
Referenced by Y.DebugPanelView.InitializeStyles, Y.DebugPanelView.OnGUI.
const string Y.DebugPanelView.delegatesCategory
Referenced by Y.DebugPanelView.DrawLog.
Vector2 Y.DebugPanelView.scrollPosition
Referenced by Y.DebugPanelView.DrawLog.
Color Y.DebugPanelView.errorColor
Referenced by Y.DebugPanelView.CategoryColor.
Color Y.DebugPanelView.systemColor
Referenced by Y.DebugPanelView.CategoryColor.
Color Y.DebugPanelView.delegateColor
Referenced by Y.DebugPanelView.CategoryColor.
Color Y.DebugPanelView.warningColor
Color Y.DebugPanelView.logColor
Referenced by Y.DebugPanelView.CategoryColor.
Color Y.DebugPanelView.defaultColor
Referenced by Y.DebugPanelView.CategoryColor.
const string Y.DebugPanelView.categoryMinus
Referenced by Y.DebugPanelView.CategoryToggle.
const string Y.DebugPanelView.categoryPlus
Referenced by Y.DebugPanelView.CategoryToggle.
static DebugPanelView Y.DebugPanelView.CreateBerryPanel()
References Y.DebugPanelView.instance.
void Y.DebugPanelView.OnEnable()
References Y.DebugPanelView.instance.
void Y.DebugPanelView.InitializeStyles()
References Y.DebugPanelView.blackTexture, Y.DebugPanelView.categoryStyle, Y.DebugPanelView.messageHeight, Y.DebugPanelView.messageNameStyle, Y.DebugPanelView.messageValueStyle, Y.DebugPanelView.outputBackgroundStyle.
Referenced by Y.DebugPanelView.OnGUI.
void Y.DebugPanelView.OnGUI()
References Y.DebugPanelView.blackTexture, Y.DebugPanelView.DrawLog, Y.DebugPanelView.DrawToolbar, Y.DebugPanelView.InitializeStyles.
void Y.DebugPanelView.DrawToolbar()
Referenced by Y.DebugPanelView.OnGUI.
void Y.DebugPanelView.DrawLog()
References Y.DebugPanel.buttons, Y.DebugPanel.categories, Y.DebugPanelView.CategoryColor, Y.DebugPanelView.categoryStyle, Y.DebugPanelView.CategoryToggle, Y.DebugPanelView.delegatesCategory, Y.DebugPanelView.DrawDelegateMessage, Y.DebugPanelView.DrawMessage, Y.DebugPanel.messages, Y.DebugPanelView.outputBackgroundStyle, Y.DebugPanelView.scrollPosition.
Referenced by Y.DebugPanelView.OnGUI.
Color Y.DebugPanelView.CategoryColor(string category)
References Y.DebugPanelView.defaultColor, Y.DebugPanelView.delegateColor, Y.DebugPanelView.errorColor, Y.DebugPanelView.logColor, Y.DebugPanelView.systemColor.
Referenced by Y.DebugPanelView.DrawLog.
string Y.DebugPanelView.CategoryToggle(bool value)
References Y.DebugPanelView.categoryMinus, Y.DebugPanelView.categoryPlus.
Referenced by Y.DebugPanelView.DrawLog.
void Y.DebugPanelView.DrawMessage(DebugPanel.Message message)
References Y.DebugPanelView.GetMessageRect, Y.DebugPanelView.messageNameStyle, Y.DebugPanelView.messageValueStyle.
Referenced by Y.DebugPanelView.DrawLog.
void Y.DebugPanelView.DrawDelegateMessage(KeyValuePair< string, Button > pair)
References Y.DebugPanelView.categoryStyle, Y.DebugPanelView.GetMessageRect, Y.DebugPanelView.messageNameStyle.
Referenced by Y.DebugPanelView.DrawLog.
Rect Y.DebugPanelView.GetMessageRect()
References Y.DebugPanelView.messageHeight.
Referenced by Y.DebugPanelView.DrawDelegateMessage, Y.DebugPanelView.DrawMessage.