Shapes2D::PolyMap
static float Shapes2D.PolyMap.DistanceToLineSegment(Vector2 pos, Vector2 p1, Vector2 p2)
Referenced by Shapes2D.PolyMap.GetClosestLineSegments.
static DistanceResult Shapes2D.PolyMap.GetClosestLineSegments(Vector2 pos, Vector2[] vertices)
References Shapes2D.PolyMap.DistanceToLineSegment, Shapes2D.PolyMap.DistanceResult.index, Shapes2D.PolyMap.DistanceResult.index2.
Referenced by Shapes2D.PolyMap.GeneratePolyMap.
static bool Shapes2D.PolyMap.PointIsInsidePoly(Vector2 pos, Vector2[] vertices)
Referenced by Shapes2D.PolyMap.GeneratePolyMap.
static bool Shapes2D.PolyMap.IntersectsVerticalLineSegment(Vector2 v1, Vector2 v2, Vector2 p1, Vector2 p2)
Referenced by Shapes2D.PolyMap.RectIntersectsPolyEdge.
static bool Shapes2D.PolyMap.IntersectsHorizontalLineSegment(Vector2 v1, Vector2 v2, Vector2 p1, Vector2 p2)
Referenced by Shapes2D.PolyMap.RectIntersectsPolyEdge.
static int Shapes2D.PolyMap.RectIntersectsPolyEdge(Vector2 tl, Vector2 tr, Vector2 bl, Vector2 br, Vector2[] vertices, bool[] results)
References Shapes2D.PolyMap.IntersectsHorizontalLineSegment, Shapes2D.PolyMap.IntersectsVerticalLineSegment.
Referenced by Shapes2D.PolyMap.GeneratePolyMap.
static int Shapes2D.PolyMap.RectContainsVertex(Vector2 tl, Vector2 tr, Vector2 bl, Vector2 br, Vector2[] vertices, bool[] results)
Referenced by Shapes2D.PolyMap.GeneratePolyMap.
static bool Shapes2D.PolyMap.PointLineTest(Vector2 pos, Vector2 p1, Vector2 p2)
Referenced by Shapes2D.PolyMap.GeneratePolyMap.
static float Shapes2D.PolyMap.GetAngleBetween(Vector2 v1, Vector2 v2)
Referenced by Shapes2D.PolyMap.GeneratePolyMap.
static void Shapes2D.PolyMap.GeneratePolyMap(Vector2[] vertices, Texture2D polyMap)
References Shapes2D.PolyMap.GetAngleBetween, Shapes2D.PolyMap.GetClosestLineSegments, Shapes2D.PolyMap.DistanceResult.index, Shapes2D.PolyMap.DistanceResult.index2, Shapes2D.PolyMap.PointIsInsidePoly, Shapes2D.PolyMap.PointLineTest, Shapes2D.PolyMap.RectContainsVertex, Shapes2D.PolyMap.RectIntersectsPolyEdge.