FastFileLog::Logger
string FastFileLog.Logger.name
Referenced by FastFileLog.Logger.Logger, FastFileLog.Logger.Save.
object FastFileLog.Logger.key
bool FastFileLog.Logger.enabled
Referenced by FastFileLog.Logger.Logger.
bool FastFileLog.Logger.printToScreen
Referenced by FastFileLog.Logger.Configure, FastFileLog.Logger.Flush, FastFileLog.Logger.Log.
bool FastFileLog.Logger.printToFile
Referenced by FastFileLog.Logger.Configure, FastFileLog.Logger.Save.
MemoryStream FastFileLog.Logger.data
Referenced by FastFileLog.Logger.Log, FastFileLog.Logger.Logger.
FileStream FastFileLog.Logger.fileWriter
Referenced by FastFileLog.Logger.Save.
System.Text.UnicodeEncoding FastFileLog.Logger.uniEncoding
Referenced by FastFileLog.Logger.WriteToStream.
bool FastFileLog.Logger.debug
Referenced by FastFileLog.Logger.Flush, FastFileLog.Logger.Log, FastFileLog.Logger.Save.
Logger FastFileLog.Logger.NullLogger
Referenced by FastFileLog.Logger.IsNull.
Logger FastFileLog.Logger._nullLogger
void FastFileLog.Logger.Configure(bool printToScreen, bool printToFile, object gameObject)
References FastFileLog.Logger.printToFile, FastFileLog.Logger.printToScreen.
void FastFileLog.Logger.Log(object logMsg)
References FastFileLog.Logger.data, FastFileLog.Logger.debug, FastFileLog.Logger.Flush, FastFileLog.Logger.LogFormat, FastFileLog.Logger.printToScreen, FastFileLog.Logger.WriteToStream.
void FastFileLog.Logger.Flush(string msg)
References FastFileLog.Logger.debug, FastFileLog.Logger.printToScreen.
Referenced by FastFileLog.Logger.Log.
void FastFileLog.Logger.Save()
References FastFileLog.Logger.debug, FastFileLog.Logger.fileWriter, FastFileLog.Logger.GetFileFullPath, FastFileLog.Logger.name, FastFileLog.Logger.printToFile.
FastFileLog.Logger.Logger(string name, bool enabled)
References FastFileLog.Logger.data, FastFileLog.Logger.enabled, FastFileLog.Logger.name, FastFileLog.Logger.WriteToStream.
virtual string FastFileLog.Logger.LogFormat(string msg)
Referenced by FastFileLog.Logger.Log.
virtual string FastFileLog.Logger.GetFileFullPath(string name)
Referenced by FastFileLog.Logger.Save.
static bool FastFileLog.Logger.IsNull(Logger l)
References FastFileLog.Logger.NullLogger.
void FastFileLog.Logger.WriteToStream(Stream stream, string msg)
References FastFileLog.Logger.uniEncoding.
Referenced by FastFileLog.Logger.Log, FastFileLog.Logger.Logger.