Win
float Win.positionDiffThreshold
Referenced by Update.
float Win.positionToSustainTime
Referenced by Update.
float Win.doorOpenProcedureTime
Referenced by DoorOpen.
float Win.paperCutFadeTime
Referenced by PaperCutFade.
float Win.timeBeforePlayerFade
Referenced by WinProcedure.
float Win.playerFadeTime
Referenced by WinProcedure.
float Win.timeBeforeNextLevel
Referenced by WinProcedure.
float Win.backGroundMusicFadeDownTime
Referenced by WinProcedure.
float Win.swordSearchRadius
Referenced by Update.
LevelManager Win.levelManager
PlayerControl Win.playerControl
Referenced by Start.
GameObject Win.player
Referenced by Start.
GameObject Win.playerBody
Referenced by Start.
GameObject Win.playerLeft
Referenced by Start.
GameObject Win.playerRight
Referenced by Start.
GameObject Win.paperCut
Referenced by Start.
GameObject Win.paperBody
Referenced by Start.
GameObject Win.paperLeft
Referenced by Start.
GameObject Win.paperRight
Referenced by Start.
GameObject Win.paperCutSword
Referenced by Start, Update, WinProcedure.
GameObject Win.door
Referenced by Start.
GameObject Win.doorIn
Referenced by Start.
GameObject Win.ledBody
Referenced by Start.
GameObject Win.ledLeft
Referenced by Start.
GameObject Win.ledRight
Referenced by Start.
GameObject Win.ledSword
Referenced by Start.
GameObject Win.colorBodyObject
Referenced by Start.
GameObject Win.colorFistObject
Referenced by Start.
Color Win.colorBody
Referenced by Start, Update.
Color Win.colorFist
Referenced by Start, Update.
Color Win.colorSword
Referenced by Start, Update.
Color Win.colorNot
Referenced by Start, Update.
LedShineTime Win.ledShineTimeBody
Referenced by Start.
LedShineTime Win.ledShineTimeLeft
Referenced by Start.
LedShineTime Win.ledShineTimeRight
Referenced by Start.
LedShineTime Win.ledShineTimeSword
Referenced by Start.
bool Win.ledJustShineBody
Referenced by Start, Update.
bool Win.ledJustShineLeft
Referenced by Start, Update.
bool Win.ledJustShineRight
Referenced by Start, Update.
bool Win.ledJustShineSword
Referenced by Start, Update.
bool Win.win
Referenced by Update, WinProcedure.
void Win.Start()
References colorBody, colorBodyObject, colorFist, colorFistObject, colorNot, colorSword, door, doorIn, ledBody, ledJustShineBody, ledJustShineLeft, ledJustShineRight, ledJustShineSword, ledLeft, ledRight, ledShineTimeBody, ledShineTimeLeft, ledShineTimeRight, ledShineTimeSword, ledSword, paperBody, paperCut, paperCutSword, paperLeft, paperRight, player, playerBody, PlayerControl.playerControl, playerControl, playerLeft, playerRight.
void Win.Update()
References colorBody, colorFist, colorNot, colorSword, ledJustShineBody, ledJustShineLeft, ledJustShineRight, ledJustShineSword, paperCutSword, positionDiffThreshold, positionToSustainTime, swordSearchRadius, win, WinProcedure.
IEnumerator Win.WinProcedure()
References backGroundMusicFadeDownTime, DoorOpen, PaperCutFade, paperCutSword, playerFadeTime, timeBeforeNextLevel, timeBeforePlayerFade, win.
Referenced by Update.
IEnumerator Win.DoorOpen()
References doorOpenProcedureTime.
Referenced by WinProcedure.
IEnumerator Win.PaperCutFade(List< SpriteRenderer > renderList)
References paperCutFadeTime.
Referenced by WinProcedure.