IngameDebugConsole::DebugLogConsole
readonly List<ConsoleMethodInfo> IngameDebugConsole.DebugLogConsole.methods
Referenced by IngameDebugConsole.DebugLogConsole.AddCommand, IngameDebugConsole.DebugLogConsole.ExecuteCommand, IngameDebugConsole.DebugLogConsole.FindCommandIndex, IngameDebugConsole.DebugLogConsole.GetAutoCompleteCommand, IngameDebugConsole.DebugLogConsole.GetCommandSuggestions, IngameDebugConsole.DebugLogConsole.LogAllCommands, IngameDebugConsole.DebugLogConsole.RemoveCommand.
readonly List<ConsoleMethodInfo> IngameDebugConsole.DebugLogConsole.matchingMethods
Referenced by IngameDebugConsole.DebugLogConsole.ExecuteCommand.
readonly Dictionary<Type, ParseFunction> IngameDebugConsole.DebugLogConsole.parseFunctions
Referenced by IngameDebugConsole.DebugLogConsole.AddCommand, IngameDebugConsole.DebugLogConsole.AddCustomParameterType, IngameDebugConsole.DebugLogConsole.ParseArgument.
readonly Dictionary<Type, string> IngameDebugConsole.DebugLogConsole.typeReadableNames
Referenced by IngameDebugConsole.DebugLogConsole.AddCustomParameterType, IngameDebugConsole.DebugLogConsole.GetTypeReadableName.
readonly List<string> IngameDebugConsole.DebugLogConsole.commandArguments
Referenced by IngameDebugConsole.DebugLogConsole.ExecuteCommand.
readonly string [] IngameDebugConsole.DebugLogConsole.inputDelimiters
Referenced by IngameDebugConsole.DebugLogConsole.IndexOfDelimiterGroup, IngameDebugConsole.DebugLogConsole.IndexOfDelimiterGroupEnd.
readonly CompareInfo IngameDebugConsole.DebugLogConsole.caseInsensitiveComparer
Referenced by IngameDebugConsole.DebugLogConsole.AddCommand, IngameDebugConsole.DebugLogConsole.DebugLogConsole, IngameDebugConsole.DebugLogConsole.ExecuteCommand, IngameDebugConsole.DebugLogConsole.GetCommandSuggestions, IngameDebugConsole.DebugLogConsole.RemoveCommand.
delegate bool IngameDebugConsole.DebugLogConsole.ParseFunction(string input, out object output)
static IngameDebugConsole.DebugLogConsole.DebugLogConsole()
References IngameDebugConsole.DebugLogConsole.AddCommand, IngameDebugConsole.DebugLogConsole.caseInsensitiveComparer, IngameDebugConsole.ConsoleMethodAttribute.Command, IngameDebugConsole.ConsoleMethodAttribute.Description, IngameDebugConsole.DebugLogConsole.LogAllCommands, IngameDebugConsole.DebugLogConsole.LogSystemInfo.
static StringBuilder IngameDebugConsole.DebugLogConsole.AppendSysInfoIfPresent(this StringBuilder sb, string info, string postfix=null)
Referenced by IngameDebugConsole.DebugLogConsole.LogSystemInfo.
static StringBuilder IngameDebugConsole.DebugLogConsole.AppendSysInfoIfPresent(this StringBuilder sb, int info, string postfix=null)
static void IngameDebugConsole.DebugLogConsole.AddCommand(string command, string description, string methodName, Type ownerType, object instance=null)
References IngameDebugConsole.DebugLogConsole.AddCommand.
static void IngameDebugConsole.DebugLogConsole.AddCommand(string command, string description, MethodInfo method, object instance=null)
References IngameDebugConsole.DebugLogConsole.caseInsensitiveComparer, IngameDebugConsole.DebugLogConsole.FindCommandIndex, IngameDebugConsole.DebugLogConsole.GetTypeReadableName, IngameDebugConsole.DebugLogConsole.IsSupportedArrayType, IngameDebugConsole.DebugLogConsole.methods, IngameDebugConsole.DebugLogConsole.parseFunctions.
static int IngameDebugConsole.DebugLogConsole.IndexOfDelimiterGroup(char c)
References IngameDebugConsole.DebugLogConsole.inputDelimiters.
Referenced by IngameDebugConsole.DebugLogConsole.FetchArgumentsFromCommand, IngameDebugConsole.DebugLogConsole.GetCommandSuggestions.
static int IngameDebugConsole.DebugLogConsole.IndexOfDelimiterGroupEnd(string command, int delimiterIndex, int startIndex)
References IngameDebugConsole.DebugLogConsole.inputDelimiters.
Referenced by IngameDebugConsole.DebugLogConsole.FetchArgumentsFromCommand, IngameDebugConsole.DebugLogConsole.GetCommandSuggestions.
static int IngameDebugConsole.DebugLogConsole.IndexOfChar(string command, char c, int startIndex)
Referenced by IngameDebugConsole.DebugLogConsole.FetchArgumentsFromCommand, IngameDebugConsole.DebugLogConsole.GetCommandSuggestions.
static int IngameDebugConsole.DebugLogConsole.FindCommandIndex(string command)
References IngameDebugConsole.DebugLogConsole.methods.
Referenced by IngameDebugConsole.DebugLogConsole.AddCommand, IngameDebugConsole.DebugLogConsole.ExecuteCommand, IngameDebugConsole.DebugLogConsole.GetAutoCompleteCommand, IngameDebugConsole.DebugLogConsole.GetCommandSuggestions.
static bool IngameDebugConsole.DebugLogConsole.ParseVector(string input, Type vectorType, out object output)
Referenced by IngameDebugConsole.DebugLogConsole.ParseBounds, IngameDebugConsole.DebugLogConsole.ParseColor, IngameDebugConsole.DebugLogConsole.ParseColor32, IngameDebugConsole.DebugLogConsole.ParseQuaternion, IngameDebugConsole.DebugLogConsole.ParseRect, IngameDebugConsole.DebugLogConsole.ParseRectOffset, IngameDebugConsole.DebugLogConsole.ParseVector2, IngameDebugConsole.DebugLogConsole.ParseVector3, IngameDebugConsole.DebugLogConsole.ParseVector4.
static void IngameDebugConsole.DebugLogConsole.LogAllCommands()
References IngameDebugConsole.DebugLogManager.Instance, IngameDebugConsole.DebugLogConsole.methods.
Referenced by IngameDebugConsole.DebugLogConsole.DebugLogConsole.
static void IngameDebugConsole.DebugLogConsole.LogSystemInfo()
References IngameDebugConsole.DebugLogConsole.AppendSysInfoIfPresent, IngameDebugConsole.DebugLogManager.Instance.
Referenced by IngameDebugConsole.DebugLogConsole.DebugLogConsole.
static void IngameDebugConsole.DebugLogConsole.AddCustomParameterType(Type type, ParseFunction parseFunction, string typeReadableName=null)
References IngameDebugConsole.DebugLogConsole.parseFunctions, IngameDebugConsole.DebugLogConsole.typeReadableNames.
static void IngameDebugConsole.DebugLogConsole.RemoveCustomParameterType(Type type)
static void IngameDebugConsole.DebugLogConsole.AddCommandInstance(string command, string description, string methodName, object instance)
References IngameDebugConsole.DebugLogConsole.AddCommand.
static void IngameDebugConsole.DebugLogConsole.AddCommandStatic(string command, string description, string methodName, Type ownerType)
References IngameDebugConsole.DebugLogConsole.AddCommand.
static void IngameDebugConsole.DebugLogConsole.AddCommand(string command, string description, Action method)
References IngameDebugConsole.DebugLogConsole.AddCommand.
Referenced by IngameDebugConsole.DebugLogConsole.AddCommand, IngameDebugConsole.DebugLogConsole.AddCommand< T1 >, IngameDebugConsole.DebugLogConsole.AddCommand< T1, T2 >, IngameDebugConsole.DebugLogConsole.AddCommand< T1, T2, T3 >, IngameDebugConsole.DebugLogConsole.AddCommand< T1, T2, T3, T4 >, IngameDebugConsole.DebugLogConsole.AddCommand< T1, T2, T3, T4, T5 >, IngameDebugConsole.DebugLogConsole.AddCommandInstance, IngameDebugConsole.DebugLogConsole.AddCommandStatic, IngameDebugConsole.DebugLogConsole.DebugLogConsole.
static void IngameDebugConsole.DebugLogConsole.AddCommand< T1 >(string command, string description, Action< T1 > method)
References IngameDebugConsole.DebugLogConsole.AddCommand.
static void IngameDebugConsole.DebugLogConsole.AddCommand< T1 >(string command, string description, Func< T1 > method)
References IngameDebugConsole.DebugLogConsole.AddCommand.
static void IngameDebugConsole.DebugLogConsole.AddCommand< T1, T2 >(string command, string description, Action< T1, T2 > method)
References IngameDebugConsole.DebugLogConsole.AddCommand.
static void IngameDebugConsole.DebugLogConsole.AddCommand< T1, T2 >(string command, string description, Func< T1, T2 > method)
References IngameDebugConsole.DebugLogConsole.AddCommand.
static void IngameDebugConsole.DebugLogConsole.AddCommand< T1, T2, T3 >(string command, string description, Action< T1, T2, T3 > method)
References IngameDebugConsole.DebugLogConsole.AddCommand.
static void IngameDebugConsole.DebugLogConsole.AddCommand< T1, T2, T3 >(string command, string description, Func< T1, T2, T3 > method)
References IngameDebugConsole.DebugLogConsole.AddCommand.
static void IngameDebugConsole.DebugLogConsole.AddCommand< T1, T2, T3, T4 >(string command, string description, Action< T1, T2, T3, T4 > method)
References IngameDebugConsole.DebugLogConsole.AddCommand.
static void IngameDebugConsole.DebugLogConsole.AddCommand< T1, T2, T3, T4 >(string command, string description, Func< T1, T2, T3, T4 > method)
References IngameDebugConsole.DebugLogConsole.AddCommand.
static void IngameDebugConsole.DebugLogConsole.AddCommand< T1, T2, T3, T4, T5 >(string command, string description, Func< T1, T2, T3, T4, T5 > method)
References IngameDebugConsole.DebugLogConsole.AddCommand.
static void IngameDebugConsole.DebugLogConsole.AddCommand(string command, string description, Delegate method)
References IngameDebugConsole.DebugLogConsole.AddCommand.
Referenced by IngameDebugConsole.DebugLogConsole.AddCommand.
static void IngameDebugConsole.DebugLogConsole.RemoveCommand(string command)
References IngameDebugConsole.DebugLogConsole.caseInsensitiveComparer, IngameDebugConsole.DebugLogConsole.methods.
Referenced by IngameDebugConsole.DebugLogConsole.RemoveCommand< T1 >, IngameDebugConsole.DebugLogConsole.RemoveCommand< T1, T2 >, IngameDebugConsole.DebugLogConsole.RemoveCommand< T1, T2, T3 >, IngameDebugConsole.DebugLogConsole.RemoveCommand< T1, T2, T3, T4 >, IngameDebugConsole.DebugLogConsole.RemoveCommand< T1, T2, T3, T4, T5 >.
static void IngameDebugConsole.DebugLogConsole.RemoveCommand(Action method)
References IngameDebugConsole.DebugLogConsole.RemoveCommand.
Referenced by IngameDebugConsole.DebugLogConsole.RemoveCommand.
static void IngameDebugConsole.DebugLogConsole.RemoveCommand< T1 >(Action< T1 > method)
References IngameDebugConsole.DebugLogConsole.RemoveCommand.
static void IngameDebugConsole.DebugLogConsole.RemoveCommand< T1 >(Func< T1 > method)
References IngameDebugConsole.DebugLogConsole.RemoveCommand.
static void IngameDebugConsole.DebugLogConsole.RemoveCommand< T1, T2 >(Action< T1, T2 > method)
References IngameDebugConsole.DebugLogConsole.RemoveCommand.
static void IngameDebugConsole.DebugLogConsole.RemoveCommand< T1, T2 >(Func< T1, T2 > method)
References IngameDebugConsole.DebugLogConsole.RemoveCommand.
static void IngameDebugConsole.DebugLogConsole.RemoveCommand< T1, T2, T3 >(Action< T1, T2, T3 > method)
References IngameDebugConsole.DebugLogConsole.RemoveCommand.
static void IngameDebugConsole.DebugLogConsole.RemoveCommand< T1, T2, T3 >(Func< T1, T2, T3 > method)
References IngameDebugConsole.DebugLogConsole.RemoveCommand.
static void IngameDebugConsole.DebugLogConsole.RemoveCommand< T1, T2, T3, T4 >(Action< T1, T2, T3, T4 > method)
References IngameDebugConsole.DebugLogConsole.RemoveCommand.
static void IngameDebugConsole.DebugLogConsole.RemoveCommand< T1, T2, T3, T4 >(Func< T1, T2, T3, T4 > method)
References IngameDebugConsole.DebugLogConsole.RemoveCommand.
static void IngameDebugConsole.DebugLogConsole.RemoveCommand< T1, T2, T3, T4, T5 >(Func< T1, T2, T3, T4, T5 > method)
References IngameDebugConsole.DebugLogConsole.RemoveCommand.
static void IngameDebugConsole.DebugLogConsole.RemoveCommand(Delegate method)
References IngameDebugConsole.DebugLogConsole.RemoveCommand.
Referenced by IngameDebugConsole.DebugLogConsole.RemoveCommand.
static void IngameDebugConsole.DebugLogConsole.RemoveCommand(MethodInfo method)
References IngameDebugConsole.DebugLogConsole.methods.
static string IngameDebugConsole.DebugLogConsole.GetAutoCompleteCommand(string commandStart)
References IngameDebugConsole.DebugLogConsole.FindCommandIndex, IngameDebugConsole.DebugLogConsole.methods.
static void IngameDebugConsole.DebugLogConsole.ExecuteCommand(string command)
References IngameDebugConsole.DebugLogConsole.caseInsensitiveComparer, IngameDebugConsole.DebugLogConsole.commandArguments, IngameDebugConsole.DebugLogConsole.FetchArgumentsFromCommand, IngameDebugConsole.DebugLogConsole.FindCommandIndex, IngameDebugConsole.DebugLogConsole.GetTypeReadableName, IngameDebugConsole.DebugLogConsole.matchingMethods, IngameDebugConsole.DebugLogConsole.methods, IngameDebugConsole.DebugLogConsole.ParseArgument.
static void IngameDebugConsole.DebugLogConsole.FetchArgumentsFromCommand(string command, List< string > commandArguments)
References IngameDebugConsole.DebugLogConsole.IndexOfChar, IngameDebugConsole.DebugLogConsole.IndexOfDelimiterGroup, IngameDebugConsole.DebugLogConsole.IndexOfDelimiterGroupEnd.
Referenced by IngameDebugConsole.DebugLogConsole.ExecuteCommand, IngameDebugConsole.DebugLogConsole.ParseArray.
static bool IngameDebugConsole.DebugLogConsole.IsSupportedArrayType(Type type)
Referenced by IngameDebugConsole.DebugLogConsole.AddCommand, IngameDebugConsole.DebugLogConsole.GetTypeReadableName, IngameDebugConsole.DebugLogConsole.ParseArgument.
static string IngameDebugConsole.DebugLogConsole.GetTypeReadableName(Type type)
References IngameDebugConsole.DebugLogConsole.IsSupportedArrayType, IngameDebugConsole.DebugLogConsole.typeReadableNames.
Referenced by IngameDebugConsole.DebugLogConsole.AddCommand, IngameDebugConsole.DebugLogConsole.ExecuteCommand.
static bool IngameDebugConsole.DebugLogConsole.ParseArgument(string input, Type argumentType, out object output)
References IngameDebugConsole.DebugLogConsole.IsSupportedArrayType, IngameDebugConsole.DebugLogConsole.ParseArray, IngameDebugConsole.DebugLogConsole.ParseComponent, IngameDebugConsole.DebugLogConsole.ParseEnum, IngameDebugConsole.DebugLogConsole.parseFunctions.
Referenced by IngameDebugConsole.DebugLogConsole.ExecuteCommand.
static bool IngameDebugConsole.DebugLogConsole.ParseString(string input, out object output)
static bool IngameDebugConsole.DebugLogConsole.ParseBool(string input, out object output)
static bool IngameDebugConsole.DebugLogConsole.ParseInt(string input, out object output)
static bool IngameDebugConsole.DebugLogConsole.ParseUInt(string input, out object output)
static bool IngameDebugConsole.DebugLogConsole.ParseLong(string input, out object output)
static bool IngameDebugConsole.DebugLogConsole.ParseULong(string input, out object output)
static bool IngameDebugConsole.DebugLogConsole.ParseByte(string input, out object output)
static bool IngameDebugConsole.DebugLogConsole.ParseSByte(string input, out object output)
static bool IngameDebugConsole.DebugLogConsole.ParseShort(string input, out object output)
static bool IngameDebugConsole.DebugLogConsole.ParseUShort(string input, out object output)
static bool IngameDebugConsole.DebugLogConsole.ParseChar(string input, out object output)
static bool IngameDebugConsole.DebugLogConsole.ParseFloat(string input, out object output)
static bool IngameDebugConsole.DebugLogConsole.ParseDouble(string input, out object output)
static bool IngameDebugConsole.DebugLogConsole.ParseDecimal(string input, out object output)
static bool IngameDebugConsole.DebugLogConsole.ParseVector2(string input, out object output)
References IngameDebugConsole.DebugLogConsole.ParseVector.
static bool IngameDebugConsole.DebugLogConsole.ParseVector3(string input, out object output)
References IngameDebugConsole.DebugLogConsole.ParseVector.
static bool IngameDebugConsole.DebugLogConsole.ParseVector4(string input, out object output)
References IngameDebugConsole.DebugLogConsole.ParseVector.
static bool IngameDebugConsole.DebugLogConsole.ParseQuaternion(string input, out object output)
References IngameDebugConsole.DebugLogConsole.ParseVector.
static bool IngameDebugConsole.DebugLogConsole.ParseColor(string input, out object output)
References IngameDebugConsole.DebugLogConsole.ParseVector.
static bool IngameDebugConsole.DebugLogConsole.ParseColor32(string input, out object output)
References IngameDebugConsole.DebugLogConsole.ParseVector.
static bool IngameDebugConsole.DebugLogConsole.ParseRect(string input, out object output)
References IngameDebugConsole.DebugLogConsole.ParseVector.
static bool IngameDebugConsole.DebugLogConsole.ParseRectOffset(string input, out object output)
References IngameDebugConsole.DebugLogConsole.ParseVector.
static bool IngameDebugConsole.DebugLogConsole.ParseBounds(string input, out object output)
References IngameDebugConsole.DebugLogConsole.ParseVector.
static bool IngameDebugConsole.DebugLogConsole.ParseGameObject(string input, out object output)
static bool IngameDebugConsole.DebugLogConsole.ParseComponent(string input, Type componentType, out object output)
Referenced by IngameDebugConsole.DebugLogConsole.ParseArgument.
static bool IngameDebugConsole.DebugLogConsole.ParseEnum(string input, Type enumType, out object output)
Referenced by IngameDebugConsole.DebugLogConsole.ParseArgument.
static bool IngameDebugConsole.DebugLogConsole.ParseArray(string input, Type arrayType, out object output)
References IngameDebugConsole.DebugLogConsole.FetchArgumentsFromCommand.
Referenced by IngameDebugConsole.DebugLogConsole.ParseArgument.
static void IngameDebugConsole.DebugLogConsole.GetCommandSuggestions(string command, List< ConsoleMethodInfo > matchingCommands, List< int > caretIndexIncrements, ref string commandName, out int numberOfParameters)
References IngameDebugConsole.DebugLogConsole.caseInsensitiveComparer, IngameDebugConsole.DebugLogConsole.FindCommandIndex, IngameDebugConsole.DebugLogConsole.IndexOfChar, IngameDebugConsole.DebugLogConsole.IndexOfDelimiterGroup, IngameDebugConsole.DebugLogConsole.IndexOfDelimiterGroupEnd, IngameDebugConsole.DebugLogConsole.methods.