FistVelocity
float FistVelocity.speedPre
Referenced by AccelerateSpeedTwoFistGrabed, FistVelocity, IsSpeedPreNoBiggerThanMaxOneFist, OffsetZeroOneHand, OffsetZeroTwoHand, RefreshSpeedOneFist.
SpeedParameter FistVelocity.speedParameter
Referenced by FistVelocity, RefreshSpeedOneFistDueToSpeedParameter.
float FistVelocity.length
Referenced by Accelerate, AccelerateTwoFistGrabed, Decelerate, FistVelocity.
float FistVelocity.speedStart
Referenced by Accelerate, AccelerateTwoFistGrabed, Decelerate, FistVelocity.
float FistVelocity.speedMaxOneFist
Referenced by Accelerate, FistVelocity, IsSpeedPreNoBiggerThanMaxOneFist, RefreshSpeedOneFistDueToSpeedParameter.
float FistVelocity.speedMaxTwoFist
Referenced by AccelerateTwoFistGrabed, FistVelocity, GetSpeedMaxTwoFist.
FistVelocity.FistVelocity(float length)
References Velocity.direction, length, Velocity.speed, speedMaxOneFist, speedMaxTwoFist, speedParameter, speedPre, speedStart.
void FistVelocity.OffsetZeroOneHand()
References Velocity.speed, speedPre.
bool FistVelocity.IsSpeedPreNoBiggerThanMaxOneFist()
References speedMaxOneFist, speedPre.
Referenced by TwoFistVelocity.OffsetReflectSpeed.
void FistVelocity.RefreshSpeedOneFist(ParameterForFistVelocity parameter)
References Velocity.direction, RefreshSpeedOneFistDueToSpeedParameter, RefreshSpeedParameterOneHand, Velocity.speed, speedPre.
void FistVelocity.OffsetZeroTwoHand()
References Velocity.speed, speedPre.
void FistVelocity.AccelerateSpeedTwoFistGrabed(ParameterForFistVelocity parameter, float speedBigger)
References AccelerateSpeedTwoFistGrabedDueToSpeedParameter, Velocity.direction, RefreshSpeedParameterTwoHand, Velocity.speed, speedPre.
float FistVelocity.GetSpeedMaxTwoFist()
References speedMaxTwoFist.
void FistVelocity.RefreshSpeedParameterOneHand(ParameterForFistVelocity parameter)
References Velocity.speed.
Referenced by RefreshSpeedOneFist.
void FistVelocity.RefreshSpeedOneFistDueToSpeedParameter(ParameterForFistVelocity parameter)
References Accelerate, Decelerate, ParameterForFistVelocity.keyDir, SpeedParameter.keyHoldState, SpeedParameter.keyReleaseTime, SpeedParameter.lastTwoHandGrabedSpeed, SpeedParameter.noTwoHandTime, Velocity.speed, SpeedParameter.speedBeforeKeyRelease, speedMaxOneFist, speedParameter.
Referenced by RefreshSpeedOneFist.
float FistVelocity.Accelerate(float speedPre)
References length, Velocity.speed, speedMaxOneFist, speedStart.
Referenced by RefreshSpeedOneFistDueToSpeedParameter.
float FistVelocity.Decelerate(float v0, float time)
References length, Velocity.speed, speedStart.
Referenced by RefreshSpeedOneFistDueToSpeedParameter.
void FistVelocity.RefreshSpeedParameterTwoHand(ParameterForFistVelocity parameter)
References Velocity.speed.
Referenced by AccelerateSpeedTwoFistGrabed.
void FistVelocity.AccelerateSpeedTwoFistGrabedDueToSpeedParameter()
References AccelerateTwoFistGrabed, Velocity.speed.
Referenced by AccelerateSpeedTwoFistGrabed.
float FistVelocity.AccelerateTwoFistGrabed(float speedPre)
References length, Velocity.speed, speedMaxTwoFist, speedStart.
Referenced by AccelerateSpeedTwoFistGrabedDueToSpeedParameter.