Shapes2D::MenuItems
Color [] Shapes2D.MenuItems.colors
Referenced by Shapes2D.MenuItems.CreatePrefab.
static bool Shapes2D.MenuItems.AddToSelected(GameObject go)
Referenced by Shapes2D.MenuItems.AddToSelectedCanvas, Shapes2D.MenuItems.AddToSelectedNonCanvas.
static void Shapes2D.MenuItems.AddToSelectedNonCanvas(GameObject go)
References Shapes2D.MenuItems.AddToSelected.
static bool Shapes2D.MenuItems.AddToSelectedCanvas(GameObject go)
References Shapes2D.MenuItems.AddToSelected.
Referenced by Shapes2D.MenuItems.CreateButton, Shapes2D.MenuItems.CreatePanel.
static GameObject Shapes2D.MenuItems.CreatePrefab(string name, bool withUndo=true)
References Shapes2D.MenuItems.colors.
static Canvas Shapes2D.MenuItems.CreateCanvas()
Referenced by Shapes2D.MenuItems.CreateButton, Shapes2D.MenuItems.CreatePanel.
static void Shapes2D.MenuItems.CreateArc()
static void Shapes2D.MenuItems.CreateCurve()
static void Shapes2D.MenuItems.CreateDonut()
static void Shapes2D.MenuItems.CreateEllipse()
static void Shapes2D.MenuItems.CreateFilledPath()
static void Shapes2D.MenuItems.CreateLinePath()
static void Shapes2D.MenuItems.CreatePie()
static void Shapes2D.MenuItems.CreatePolygon()
static void Shapes2D.MenuItems.CreateRectangle()
static void Shapes2D.MenuItems.CreateRoundedRectangle()
static void Shapes2D.MenuItems.CreateTriangle()
static void Shapes2D.MenuItems.CreateButton()
References Shapes2D.MenuItems.AddToSelectedCanvas, Shapes2D.MenuItems.CreateCanvas.
static void Shapes2D.MenuItems.CreatePanel()
References Shapes2D.MenuItems.AddToSelectedCanvas, Shapes2D.MenuItems.CreateCanvas.