HandRepresent
GameObject HandRepresent.rightJoint1
Referenced by HandRepresent, RefreshRight.
GameObject HandRepresent.rightJoint2
Referenced by HandRepresent, RefreshRight.
GameObject HandRepresent.rightLine1
Referenced by HandRepresent, RefreshRight.
GameObject HandRepresent.rightLine2
Referenced by HandRepresent, RefreshRight.
GameObject HandRepresent.rightFist
Referenced by HandRepresent, RefreshRight.
GameObject HandRepresent.leftJoint1
Referenced by HandRepresent, RefreshLeft.
GameObject HandRepresent.leftJoint2
Referenced by HandRepresent, RefreshLeft.
GameObject HandRepresent.leftLine1
Referenced by HandRepresent, RefreshLeft.
GameObject HandRepresent.leftLine2
Referenced by HandRepresent, RefreshLeft.
GameObject HandRepresent.leftFist
Referenced by HandRepresent, RefreshLeft.
float HandRepresent.length1
Referenced by GetShapeRightJoint2Pos_OptimizedAlwaysLeft, GetShapeRightJoint2Pos_Reflect, GetShapeRightJoint2Pos_SimpleAlwaysLeft, HandRepresent, RefreshLeft, RefreshRight.
float HandRepresent.length2
Referenced by GetShapeRightJoint2Pos_OptimizedAlwaysLeft, GetShapeRightJoint2Pos_Reflect, GetShapeRightJoint2Pos_SimpleAlwaysLeft, HandRepresent, RefreshLeft, RefreshRight.
float HandRepresent.length
Referenced by GetShapeRightJoint2Pos_OptimizedAlwaysLeft, GetShapeRightJoint2Pos_Reflect, GetShapeRightJoint2Pos_SimpleAlwaysLeft, HandRepresent, RefreshLeft, RefreshRight.
Joint2State HandRepresent.rightJoint2State
Referenced by HandRepresent, Refresh, RefreshRight.
Joint2State HandRepresent.leftJoint2State
Referenced by HandRepresent, Refresh, RefreshLeft.
Joint2State HandRepresent.rightJoint2StatePre
Referenced by HandRepresent, Refresh, RefreshRight.
Joint2State HandRepresent.leftJoint2StatePre
Referenced by Refresh, RefreshLeft.
Vector2 HandRepresent.rightFistPosPre
Referenced by HandRepresent, Refresh, RefreshRight.
Vector2 HandRepresent.leftFistPosPre
Referenced by HandRepresent, Refresh, RefreshLeft.
bool HandRepresent.currentLR
Referenced by GetShapeRightJoint2Pos_Reflect, GetShapeRightOther, RefreshLeft, RefreshRight.
HandRepresent.HandRepresent(GameObject whole)
References leftFist, leftFistPosPre, leftJoint1, leftJoint2, leftJoint2State, leftLine1, leftLine2, length, length1, length2, Line, rightFist, rightFistPosPre, rightJoint1, rightJoint2, rightJoint2State, rightJoint2StatePre, rightLine1, rightLine2.
void HandRepresent.Refresh()
References leftFistPosPre, leftJoint2State, leftJoint2StatePre, RefreshLeft, RefreshRight, rightFistPosPre, rightJoint2State, rightJoint2StatePre.
void HandRepresent.RefreshRight()
References CalulateShapeRight, CalulateShapeRight2, currentLR, length, length1, length2, rightFist, rightFistPosPre, rightJoint1, rightJoint2, rightJoint2State, rightJoint2StatePre, rightLine1, rightLine2.
Referenced by Refresh.
void HandRepresent.RefreshLeft()
References CalulateShapeRight, currentLR, leftFist, leftFistPosPre, leftJoint1, leftJoint2, leftJoint2State, leftJoint2StatePre, leftLine1, leftLine2, length, length1, length2.
Referenced by Refresh.
static void HandRepresent.CalulateShapeRight(in Vector2 fistPos, in Vector2 fistPosPre, in Vector2 joint1Pos, in Vector2 joint2PosPre, in Joint2State joint2StatePre, in float joint1ScaleX, in float joint2ScaleX, in float line1ScaleX, in float line2ScaleX, in float length1, in float length2, in float length, out Vector2 joint2Pos, out Joint2State joint2State, out Vector2 line1Pos, out Quaternion line1Rotation, out Vector2 line2Pos, out Quaternion line2Rotation, out Quaternion fistRotation)
References GetShapeRightJoint2Pos_OptimizedAlwaysLeft, GetShapeRightOther.
Referenced by RefreshLeft, RefreshRight.
static void HandRepresent.CalulateShapeRight2(in Vector2 fistPos, in Vector2 fistPosPre, in Vector2 joint1Pos, in Vector2 joint2PosPre, in Joint2State joint2StatePre, in float joint1ScaleX, in float joint2ScaleX, in float line1ScaleX, in float line2ScaleX, in float length1, in float length2, in float length, out Vector2 joint2Pos, out Joint2State joint2State, out Vector2 line1Pos, out Quaternion line1Rotation, out Vector2 line2Pos, out Quaternion line2Rotation, out Quaternion fistRotation)
References GetShapeRightJoint2Pos_SimpleAlwaysLeft, GetShapeRightOther.
Referenced by RefreshRight.
static void HandRepresent.GetShapeRightJoint2Pos_Reflect(in Vector2 fistPos, in Vector2 fistPosPre, in Vector2 joint1Pos, in Vector2 joint2PosPre, in Joint2State joint2StatePre, in float length1, in float length2, in float length, out Vector2 joint2Pos, out Joint2State joint2State)
References currentLR, length, length1, length2, Line, Singularity, TriangleLeft, TriangleRight.
static void HandRepresent.GetShapeRightJoint2Pos_SimpleAlwaysLeft(in Vector2 fistPos, in Vector2 fistPosPre, in Vector2 joint1Pos, in Vector2 joint2PosPre, in Joint2State joint2StatePre, in float length1, in float length2, in float length, out Vector2 joint2Pos, out Joint2State joint2State)
References length, length1, length2, Line, Singularity, TriangleLeft.
Referenced by CalulateShapeRight2.
static void HandRepresent.GetShapeRightJoint2Pos_OptimizedAlwaysLeft(in Vector2 fistPos, in Vector2 fistPosPre, in Vector2 joint1Pos, in Vector2 joint2PosPre, in Joint2State joint2StatePre, in float length1, in float length2, in float length, out Vector2 joint2Pos, out Joint2State joint2State)
References length, length1, length2, Line, Singularity, TriangleLeft.
Referenced by CalulateShapeRight.
static void HandRepresent.GetShapeRightOther(in Vector2 fistPos, in Vector2 joint1Pos, in Vector2 joint2Pos, in float joint1ScaleX, in float joint2ScaleX, in float line1ScaleX, in float line2ScaleX, in float length1, in float length2, in float length, out Vector2 line1Pos, out Quaternion line1Rotation, out Vector2 line2Pos, out Quaternion line2Rotation, out Quaternion fistRotation)
References currentLR.
Referenced by CalulateShapeRight, CalulateShapeRight2.