Shapes2D::InputUtils
static Vector3 Shapes2D.InputUtils.InputToWorldPosition(Vector2 inputPos)
static bool Shapes2D.InputUtils.MouseDownOrTap()
References Shapes2D.InputUtils.WasFingerDown, Shapes2D.InputUtils.WasMouseDown.
Referenced by Shapes2D.EffectDemo.Update, Shapes2D.Bird.Update.
static Vector2 Shapes2D.InputUtils.MouseOrTapPosition()
References Shapes2D.InputUtils.FirstTouchPosition.
static bool Shapes2D.InputUtils.WasMouseDown(int button)
Referenced by Shapes2D.InputUtils.MouseDownOrTap.
static bool Shapes2D.InputUtils.WasFingerDown()
Referenced by Shapes2D.InputUtils.MouseDownOrTap.
static Vector2 Shapes2D.InputUtils.FirstTouchPosition()
Referenced by Shapes2D.InputUtils.MouseOrTapPosition.