HKey
bool HKey.debugModOn
Referenced by EasyDebug.Update, Update.
DebugMod HKey.debugMod
Referenced by DebugModUpdateRefresh.
bool HKey.lAnyDirKeyHold_Keyboard
Referenced by DeviceToOperation, Keyboard.
bool HKey.rAnyDirKeyHold_Keyboard
Referenced by DeviceToOperation, Keyboard.
bool HKey.lAnyDirKeyHold_Gamepad
Referenced by DeviceToOperation, GamePad.
bool HKey.rAnyDirKeyHold_Gamepad
Referenced by DeviceToOperation, GamePad.
bool HKey.lAnyDirKeyHold
Referenced by DeviceToOperation, PlayerControl.FU_FistOffetInfluenceSpeed, PlayerControl.FU_FistSpeed.
bool HKey.rAnyDirKeyHold
Referenced by DeviceToOperation, PlayerControl.FU_FistOffetInfluenceSpeed, PlayerControl.FU_FistSpeed.
Vector2 HKey.lMvDir
Referenced by DeviceToOperation, PlayerControl.FU_FistOffetInfluenceSpeed, PlayerControl.FU_FistSpeed, PlayerControl.HandStuffFixedUpdate.
Vector2 HKey.rMvDir
Referenced by DeviceToOperation, PlayerControl.FU_FistOffetInfluenceSpeed, PlayerControl.FU_FistSpeed, PlayerControl.HandStuffFixedUpdate.
bool HKey.lGrab
Referenced by DebugModUpdateRefresh, DeviceToOperation, PlayerControl.FU_Pre.
bool HKey.rGrab
Referenced by DebugModUpdateRefresh, DeviceToOperation, PlayerControl.FU_Pre.
UnityEngine.InputSystem.Gamepad HKey.gamepad
Referenced by DeviceToOperation, GamePad, Start.
UnityEngine.InputSystem.Keyboard HKey.keyboard
Referenced by DebugModUpdateRefresh, DeviceToOperation, Keyboard, Start.
bool HKey.lUp
Referenced by Keyboard.
bool HKey.lDown
Referenced by Keyboard.
bool HKey.lLeft
Referenced by Keyboard.
bool HKey.lRight
Referenced by Keyboard.
int HKey.lMvRight
Referenced by DeviceToOperation, Keyboard.
int HKey.lMvUp
Referenced by DeviceToOperation, Keyboard.
bool HKey.rUp
Referenced by Keyboard.
bool HKey.rDown
Referenced by Keyboard.
bool HKey.rLeft
Referenced by Keyboard.
bool HKey.rRight
Referenced by Keyboard.
int HKey.rMvRight
Referenced by DeviceToOperation, Keyboard.
int HKey.rMvUp
Referenced by DeviceToOperation, Keyboard.
bool HKey.lAlt
Referenced by DeviceToOperation, Keyboard.
bool HKey.rAlt
Referenced by DeviceToOperation, Keyboard.
Vector2 HKey.leftStick
Referenced by DeviceToOperation, GamePad.
Vector2 HKey.rightStick
Referenced by DeviceToOperation, GamePad.
bool HKey.leftTrigger
Referenced by DeviceToOperation, GamePad.
bool HKey.rightTrigger
Referenced by DeviceToOperation, GamePad.
void HKey.Start()
References gamepad, keyboard.
void HKey.Update()
References debugModOn, DebugModUpdateRefresh, DeviceToOperation, GamePad, Keyboard.
static void HKey.Keyboard()
References keyboard, lAlt, lAnyDirKeyHold_Keyboard, lDown, lLeft, lMvRight, lMvUp, lRight, lUp, rAlt, rAnyDirKeyHold_Keyboard, rDown, rLeft, rMvRight, rMvUp, rRight, rUp.
Referenced by DebugModUpdateRefresh, Update.
static void HKey.GamePad()
References gamepad, lAnyDirKeyHold_Gamepad, leftStick, leftTrigger, rAnyDirKeyHold_Gamepad, rightStick, rightTrigger.
Referenced by DebugModUpdateRefresh, Update.
static void HKey.DeviceToOperation()
References gamepad, keyboard, lAlt, lAnyDirKeyHold, lAnyDirKeyHold_Gamepad, lAnyDirKeyHold_Keyboard, leftStick, leftTrigger, lGrab, lMvDir, lMvRight, lMvUp, rAlt, rAnyDirKeyHold, rAnyDirKeyHold_Gamepad, rAnyDirKeyHold_Keyboard, rGrab, rightStick, rightTrigger, rMvDir, rMvRight, rMvUp.
Referenced by DebugModUpdateRefresh, Update.
static void HKey.DebugModUpdateRefresh()
References debugMod, DeviceToOperation, GamePad, keyboard, Keyboard, lGrab, HKey.DebugMod.lGrabAlways, rGrab, HKey.DebugMod.rGrabAlways.
Referenced by Update.