PluginMaster::PlayModeSave
SaveCommand
const string PluginMaster.PlayModeSave.TOOL_NAME
const string PluginMaster.PlayModeSave.AUTO_SAVE_PREF
Referenced by PluginMaster.PlayModeSave.LoadPrefs, PluginMaster.PlayModeSave.OnDisable, PluginMaster.PlayModeSave.OnGUI.
const string PluginMaster.PlayModeSave.AUTO_SAVE_PERIOD_PREF
Referenced by PluginMaster.PlayModeSave.LoadPrefs, PluginMaster.PlayModeSave.OnDisable, PluginMaster.PlayModeSave.OnGUI.
const string PluginMaster.PlayModeSave.AUTO_APPLY_PREF
Referenced by PluginMaster.PlayModeSave.LoadPrefs, PluginMaster.PlayModeSave.OnDisable, PluginMaster.PlayModeSave.OnGUI.
bool PluginMaster.PlayModeSave._autoApply
Referenced by PluginMaster.PlayModeSave.LoadPrefs, PluginMaster.PlayModeSave.OnDisable, PluginMaster.PlayModeSave.OnGUI, PluginMaster.PlayModeSave.ApplicationEventHandler.OnStateChanged.
bool PluginMaster.PlayModeSave._autoSave
Referenced by PluginMaster.PlayModeSave.AutoSave, PluginMaster.PlayModeSave.LoadPrefs, PluginMaster.PlayModeSave.OnDisable, PluginMaster.PlayModeSave.OnGUI, PluginMaster.PlayModeSave.ApplicationEventHandler.OnStateChanged.
int PluginMaster.PlayModeSave._autoSavePeriod
Referenced by PluginMaster.PlayModeSave.AutoSave, PluginMaster.PlayModeSave.LoadPrefs, PluginMaster.PlayModeSave.OnDisable, PluginMaster.PlayModeSave.OnGUI.
Dictionary<ComponentSaveDataKey, SaveDataValue> PluginMaster.PlayModeSave._compData
Referenced by PluginMaster.PlayModeSave.Add, PluginMaster.PlayModeSave.Apply, PluginMaster.PlayModeSave.AutoSave, PluginMaster.PlayModeSave.OnGUI, PluginMaster.PlayModeSave.ApplicationEventHandler.OnStateChanged.
static bool PluginMaster.PlayModeSave.ValidateSaveNowMenu(MenuCommand command)
static void PluginMaster.PlayModeSave.SaveNowMenu(MenuCommand command)
static bool PluginMaster.PlayModeSave.ValidateSaveOnExtiMenu(MenuCommand command)
static void PluginMaster.PlayModeSave.SaveOnExitMenu(MenuCommand command)
static bool PluginMaster.PlayModeSave.ValidateApplyMenu(MenuCommand command)
static void PluginMaster.PlayModeSave.ApplyMenu(MenuCommand command)
static void PluginMaster.PlayModeSave.SaveScriptableObject(MenuCommand command)
static bool PluginMaster.PlayModeSave.CheckIsNotPlaying()
static void PluginMaster.PlayModeSave.ShowWindow()
static void PluginMaster.PlayModeSave.LoadPrefs()
References PluginMaster.PlayModeSave._autoApply, PluginMaster.PlayModeSave._autoSave, PluginMaster.PlayModeSave._autoSavePeriod, PluginMaster.PlayModeSave.AUTO_APPLY_PREF, PluginMaster.PlayModeSave.AUTO_SAVE_PERIOD_PREF, PluginMaster.PlayModeSave.AUTO_SAVE_PREF.
Referenced by PluginMaster.PlayModeSave.ApplicationEventHandler.ApplicationEventHandler.
static ComponentSaveDataKey PluginMaster.PlayModeSave.GetKey(Object comp)
static void PluginMaster.PlayModeSave.Add(Component component, SaveCommand cmd)
References PluginMaster.PlayModeSave._compData.
static async void PluginMaster.PlayModeSave.AutoSave()
References PluginMaster.PlayModeSave._autoSave, PluginMaster.PlayModeSave._autoSavePeriod, PluginMaster.PlayModeSave._compData.
Referenced by PluginMaster.PlayModeSave.OnGUI, PluginMaster.PlayModeSave.ApplicationEventHandler.OnStateChanged.
static void PluginMaster.PlayModeSave.RemoveNewObjects()
static void PluginMaster.PlayModeSave.Apply(ComponentSaveDataKey key)
References PluginMaster.PlayModeSave._compData.
Referenced by PluginMaster.PlayModeSave.ApplyAll.
static void PluginMaster.PlayModeSave.ApplyAll()
References PluginMaster.PlayModeSave.Apply.
Referenced by PluginMaster.PlayModeSave.OnGUI.
void PluginMaster.PlayModeSave.OnEnable()
void PluginMaster.PlayModeSave.OnDisable()
References PluginMaster.PlayModeSave._autoApply, PluginMaster.PlayModeSave._autoSave, PluginMaster.PlayModeSave._autoSavePeriod, PluginMaster.PlayModeSave.AUTO_APPLY_PREF, PluginMaster.PlayModeSave.AUTO_SAVE_PERIOD_PREF, PluginMaster.PlayModeSave.AUTO_SAVE_PREF.
void PluginMaster.PlayModeSave.OnGUI()
References PluginMaster.PlayModeSave._autoApply, PluginMaster.PlayModeSave._autoSave, PluginMaster.PlayModeSave._autoSavePeriod, PluginMaster.PlayModeSave._compData, PluginMaster.PlayModeSave.ApplyAll, PluginMaster.PlayModeSave.AUTO_APPLY_PREF, PluginMaster.PlayModeSave.AUTO_SAVE_PERIOD_PREF, PluginMaster.PlayModeSave.AUTO_SAVE_PREF, PluginMaster.PlayModeSave.AutoSave.