SpeedParameter
bool SpeedParameter.keyHoldState
Referenced by RefreshOneHand, RefreshSpeedBeforeKeyRelease, FistVelocity.RefreshSpeedOneFistDueToSpeedParameter, RefreshTime, RefreshTwoHand, SpeedParameter.
bool SpeedParameter.keyHoldStatePre
Referenced by RefreshOneHand, RefreshSpeedBeforeKeyRelease, RefreshTime, RefreshTwoHand, SpeedParameter.
float SpeedParameter.keyReleaseTime
Referenced by FistVelocity.RefreshSpeedOneFistDueToSpeedParameter, RefreshTime, SpeedParameter.
float SpeedParameter.speedBeforeKeyRelease
Referenced by RefreshSpeedBeforeKeyRelease, FistVelocity.RefreshSpeedOneFistDueToSpeedParameter, SpeedParameter.
bool SpeedParameter.preIsTwoHand
Referenced by RefreshLastTwoHandGrabedSpeed, RefreshNoTwoHandTime, RefreshOneHand, RefreshTwoHand, SpeedParameter.
bool SpeedParameter.nowIsTwoHand
Referenced by RefreshLastTwoHandGrabedSpeed, RefreshNoTwoHandTime, RefreshOneHand, RefreshTwoHand, SpeedParameter.
float SpeedParameter.noTwoHandTime
Referenced by RefreshNoTwoHandTime, FistVelocity.RefreshSpeedOneFistDueToSpeedParameter, SpeedParameter.
float SpeedParameter.lastTwoHandGrabedSpeed
Referenced by RefreshLastTwoHandGrabedSpeed, FistVelocity.RefreshSpeedOneFistDueToSpeedParameter, SpeedParameter.
SpeedParameter.SpeedParameter()
References keyHoldState, keyHoldStatePre, keyReleaseTime, lastTwoHandGrabedSpeed, noTwoHandTime, nowIsTwoHand, preIsTwoHand, speedBeforeKeyRelease.
void SpeedParameter.RefreshOneHand(bool newKeyHoldState, float speed)
References keyHoldState, keyHoldStatePre, nowIsTwoHand, preIsTwoHand, RefreshLastTwoHandGrabedSpeed, RefreshNoTwoHandTime, RefreshSpeedBeforeKeyRelease, RefreshTime.
void SpeedParameter.RefreshTwoHand(bool newKeyHoldState, float speed)
References keyHoldState, keyHoldStatePre, nowIsTwoHand, preIsTwoHand, RefreshLastTwoHandGrabedSpeed, RefreshNoTwoHandTime, RefreshSpeedBeforeKeyRelease, RefreshTime.
void SpeedParameter.RefreshSpeedBeforeKeyRelease(float speed)
References keyHoldState, keyHoldStatePre, speedBeforeKeyRelease.
Referenced by RefreshOneHand, RefreshTwoHand.
void SpeedParameter.RefreshTime()
References keyHoldState, keyHoldStatePre, keyReleaseTime.
Referenced by RefreshOneHand, RefreshTwoHand.
void SpeedParameter.RefreshLastTwoHandGrabedSpeed(float speed)
References lastTwoHandGrabedSpeed, nowIsTwoHand, preIsTwoHand.
Referenced by RefreshOneHand, RefreshTwoHand.
void SpeedParameter.RefreshNoTwoHandTime()
References noTwoHandTime, nowIsTwoHand, preIsTwoHand.
Referenced by RefreshOneHand, RefreshTwoHand.