PivotUtilities
Edge
static void PivotUtilities.CreatePivotObject()
static void PivotUtilities.CreatePivotObjectAtParentPos()
static void PivotUtilities.DeletePivotObject()
static void PivotUtilities.CreatePivotLeft()
References CreatePivotObjectAtOneEdge.
static void PivotUtilities.CreatePivotRight()
References CreatePivotObjectAtOneEdge.
static void PivotUtilities.CreatePivotBottom()
References CreatePivotObjectAtOneEdge.
static void PivotUtilities.CreatePivotTop()
References CreatePivotObjectAtOneEdge.
static GameObject PivotUtilities.CreatePivotObjectAtParentPos(GameObject current)
static GameObject PivotUtilities.CreatePivotObject(GameObject current)
static GameObject PivotUtilities.DeletePivotObject(GameObject current)
static GameObject PivotUtilities.CreatePivotObjectAtOneEdge(GameObject current, Edge edge)
Referenced by CreatePivotBottom, CreatePivotLeft, CreatePivotRight, CreatePivotTop.