LevelManager
LevelManager LevelManager.onlyInstance
Referenced by Awake, OnDestroy, CameraFollow.Start.
float LevelManager.firstStartScreenStillTime
Referenced by FirstStartCoroutine.
float LevelManager.firstStartScreenFadeTime
Referenced by FirstStartCoroutine.
float LevelManager.fadeOffTime
Referenced by GameRestartCoroutine.
float LevelManager.litUpTime
Referenced by GameRestartCoroutine.
float LevelManager.collideEnemyTime
Referenced by PlayerCollideEnemy.
bool LevelManager.playerRestartOn
Referenced by FixedUpdate, GameRestartCoroutine.
bool LevelManager.playerMeetEnemyOn
Referenced by FixedUpdate, PlayerCollideEnemy.
GameObject LevelManager.playerHead
Referenced by InitFields.
Collider2D LevelManager.playerCollider
Referenced by FixedUpdate, InitFields.
AABB LevelManager.region
Referenced by FixedUpdate, InitFields.
void LevelManager.Awake()
References FirstStartCoroutine, InitFields, onlyInstance.
void LevelManager.OnDestroy()
References onlyInstance.
void LevelManager.InitFields()
References playerCollider, playerHead, region.
Referenced by Awake, GameRestartCoroutine.
void LevelManager.Update()
void LevelManager.FixedUpdate()
References LevelManager.AABB.bottom, LevelManager.AABB.left, PlayerCollideEnemy, playerCollider, playerMeetEnemyOn, PlayerOutOfRange, playerRestartOn, region, LevelManager.AABB.right.
void LevelManager.PlayerDiePre()
References PlayerControl.playerControl.
Referenced by PlayerCollideEnemy, PlayerOutOfRange.
void LevelManager.PlayerOutOfRange()
References GameRestartCoroutine, PlayerDiePre.
Referenced by FixedUpdate.
IEnumerator LevelManager.FirstStartCoroutine()
References firstStartScreenFadeTime, firstStartScreenStillTime.
Referenced by Awake.
IEnumerator LevelManager.PlayerCollideEnemy(GameObject enemyObj)
References collideEnemyTime, GameRestartCoroutine, PlayerDiePre, playerMeetEnemyOn.
Referenced by FixedUpdate.
IEnumerator LevelManager.GameRestartCoroutine()
References fadeOffTime, InitFields, litUpTime, PlayerControl.playerControl, playerRestartOn.
Referenced by PlayerCollideEnemy, PlayerOutOfRange.
void LevelManager.NextLevel()