Ludo::LogFile
LogFile Ludo.LogFile.instance
Referenced by Ludo.LogFile.Awake, Ludo.LogFile.Log, Ludo.LogFile.LogTemp, Ludo.LogFile.LogTemp2.
string Ludo.LogFile.path
Referenced by Ludo.LogFile.Awake.
string Ludo.LogFile.filename
Referenced by Ludo.LogFile.Awake.
StringBuilder Ludo.LogFile.buffer
Referenced by Ludo.LogFile.Flush.
StreamWriter Ludo.LogFile.writer
Referenced by Ludo.LogFile.Awake.
float Ludo.LogFile.flushTime
Referenced by Ludo.LogFile.Update.
float Ludo.LogFile.flushInterval
Referenced by Ludo.LogFile.Update.
string Ludo.LogFile.filenameTemp
Referenced by Ludo.LogFile.Awake.
StringBuilder Ludo.LogFile.bufferTemp
Referenced by Ludo.LogFile.Flush.
StreamWriter Ludo.LogFile.writerTemp
Referenced by Ludo.LogFile.Awake.
string Ludo.LogFile.filenameTemp2
Referenced by Ludo.LogFile.Awake.
StringBuilder Ludo.LogFile.bufferTemp2
Referenced by Ludo.LogFile.Flush.
StreamWriter Ludo.LogFile.writerTemp2
Referenced by Ludo.LogFile.Awake.
string Ludo.LogFile.fullFilename
Referenced by Ludo.LogFile.Awake.
string Ludo.LogFile.fullFilenameTemp
Referenced by Ludo.LogFile.Awake.
string Ludo.LogFile.fullFilenameTemp2
Referenced by Ludo.LogFile.Awake.
bool Ludo.LogFile.createNewFile
Referenced by Ludo.LogFile.Awake.
bool Ludo.LogFile.ifOldFileClearOldFile
Referenced by Ludo.LogFile.Awake.
void Ludo.LogFile.Awake()
References Ludo.LogFile.createNewFile, Ludo.LogFile.filename, Ludo.LogFile.filenameTemp, Ludo.LogFile.filenameTemp2, Ludo.LogFile.fullFilename, Ludo.LogFile.fullFilenameTemp, Ludo.LogFile.fullFilenameTemp2, Ludo.LogFile.ifOldFileClearOldFile, Ludo.LogFile.instance, Ludo.LogFile.Log, Ludo.LogFile.LogTemp, Ludo.LogFile.LogTemp2, Ludo.LogFile.path, Ludo.LogFile.writer, Ludo.LogFile.writerTemp, Ludo.LogFile.writerTemp2.
void Ludo.LogFile.OnDestroy()
References Ludo.LogFile.Flush, Ludo.LogFile.Log, Ludo.LogFile.LogTemp, Ludo.LogFile.LogTemp2.
void Ludo.LogFile.Update()
References Ludo.LogFile.Flush, Ludo.LogFile.flushInterval, Ludo.LogFile.flushTime.
void Ludo.LogFile.Flush()
References Ludo.LogFile.buffer, Ludo.LogFile.bufferTemp, Ludo.LogFile.bufferTemp2.
Referenced by Ludo.LogFile.OnDestroy, Ludo.LogFile.Update.
static void Ludo.LogFile.Log(string message)
References Ludo.LogFile.instance.
Referenced by Ludo.LogFile.Awake, Ludo.LogFile.OnDestroy.
static void Ludo.LogFile.LogTemp(string message)
References Ludo.LogFile.instance.
Referenced by Ludo.LogFile.Awake, Ludo.LogFile.OnDestroy.
static void Ludo.LogFile.LogTemp2(string message)
References Ludo.LogFile.instance.
Referenced by Ludo.LogFile.Awake, Ludo.LogFile.OnDestroy.