Y::SceneResearch
Dictionary<string, Func<string[], IEnumerator> > Y.SceneResearch.sublogics
Referenced by Y.SceneResearch.Execute, Y.SceneResearch.SceneResearch.
GameObject Y.SceneResearch.currentObject
Referenced by Y.SceneResearch.DestroySelected, Y.SceneResearch.ListOfChilds, Y.SceneResearch.PrintDetails, Y.SceneResearch.SelectChild.
Y.SceneResearch.SceneResearch()
References Y.SceneResearch.DestroySelected, Y.SceneResearch.ListOfChilds, Y.SceneResearch.PrintDetails, Y.SceneResearch.SelectChild, Y.SceneResearch.sublogics.
override string Y.SceneResearch.Help()
References Y.SceneResearch.GetName.
override IEnumerator Y.SceneResearch.Execute(params string[] args)
References Y.SceneResearch.sublogics.
override string Y.SceneResearch.GetName()
Referenced by Y.SceneResearch.Help.
IEnumerator Y.SceneResearch.ListOfChilds(params string[] args)
References Y.SceneResearch.Childs, Y.SceneResearch.currentObject.
Referenced by Y.SceneResearch.SceneResearch.
IEnumerator Y.SceneResearch.DestroySelected(params string[] args)
References Y.SceneResearch.currentObject.
Referenced by Y.SceneResearch.SceneResearch.
IEnumerator Y.SceneResearch.SelectChild(params string[] args)
References Y.SceneResearch.Childs, Y.SceneResearch.currentObject.
Referenced by Y.SceneResearch.SceneResearch.
IEnumerator Y.SceneResearch.PrintDetails(params string[] args)
References Y.SceneResearch.currentObject.
Referenced by Y.SceneResearch.SceneResearch.
GameObject [] Y.SceneResearch.Childs(GameObject gameObject)
Referenced by Y.SceneResearch.ListOfChilds, Y.SceneResearch.SelectChild.