WholeVelocityWhileJumping
StartJump_Direction_Type
float WholeVelocityWhileJumping.gravity
Referenced by FixedUpdateManually, WholeVelocityWhileJumping.
float WholeVelocityWhileJumping.friction
Referenced by WholeVelocityWhileJumping.
float WholeVelocityWhileJumping.speedDownPartMax
Referenced by FixedUpdateManually, WholeVelocityWhileJumping.
float WholeVelocityWhileJumping.wholeFistSpeedRatio
Referenced by StartJump_GetSpeed_FromEqualToBeforeJump_ToSpeed, WholeVelocityWhileJumping.
float WholeVelocityWhileJumping.historyTime
Referenced by WholeVelocityWhileJumping.
float WholeVelocityWhileJumping.historyZeroCutTime
Referenced by StartJump_GetDirection, StartJump_GetSpeed_EqualToBeforeJump, WholeVelocityWhileJumping.
float WholeVelocityWhileJumping.historySimpleHistoryTime
Referenced by StartJump_GetDirection, WholeVelocityWhileJumping.
float WholeVelocityWhileJumping.historyComplexHistoryTime
Referenced by StartJump_GetDirection, WholeVelocityWhileJumping.
bool WholeVelocityWhileJumping.jumpSpeedAddedWhenSlanting
Referenced by StartJump_SpeedAddedWhenSlanting, WholeVelocityWhileJumping.
string WholeVelocityWhileJumping.startJumpLog
Referenced by StartJump, StartJumpWithLog.
Vector2 WholeVelocityWhileJumping::direction
Referenced by FixedUpdateManually, StartJump, StartJump_GetDirection, StartJump_SpeedAddedWhenSlanting.
WholeVelocityWhileJumping.WholeVelocityWhileJumping(float gravity, float friction, float speedDownPartMax, float wholeFistSpeedRatio, float historyTime, float historyZeroCutTime, float historySimpleHistoryTime, float historyComplexHistoryTime, bool jumpSpeedAddedWhenSlanting)
References friction, gravity, historyComplexHistoryTime, historySimpleHistoryTime, historyTime, historyZeroCutTime, jumpSpeedAddedWhenSlanting, speedDownPartMax, wholeFistSpeedRatio.
void WholeVelocityWhileJumping.StartJumpWithLog(WholeVelocityBeforeJump velocityBeforeJump, WholeOffset offset)
References WholeVelocityBeforeJump.history, StartJump, startJumpLog.
float WholeVelocityWhileJumping.Out_GetSpeed_EqualToBeforeJump(WholeVelocityBeforeJump velocityBeforeJump, StartJump_Direction_Type type)
References StartJump_GetSpeed_EqualToBeforeJump.
void WholeVelocityWhileJumping.FixedUpdateManually(Params @params)
References direction, gravity, FistStatePlus.IsGrabing_Env_StuffEnv, Velocity.speed, speedDownPartMax, Velocity.velocity.
void WholeVelocityWhileJumping.StartJump(WholeVelocityBeforeJump velocityBeforeJump, WholeOffset offset)
References direction, Velocity.speed, StartJump_GetDirection, StartJump_GetSpeed, StartJump_SpeedAddedWhenSlanting, startJumpLog.
Referenced by StartJumpWithLog.
Vector2 StartJump_Direction_Type type WholeVelocityWhileJumping.StartJump_GetDirection(WholeVelocityBeforeJump velocityBeforeJump)
References direction, WholeVelocityBeforeJump.history, historyComplexHistoryTime, historySimpleHistoryTime, historyZeroCutTime, Velocity.speed.
Referenced by Out_GetDirection, StartJump.
float WholeVelocityWhileJumping.StartJump_GetSpeed(WholeVelocityBeforeJump velocityBeforeJump, StartJump_Direction_Type type, out float lastNoZeroSpeedOut, out float deltaTimeOut)
References StartJump_GetSpeed_EqualToBeforeJump, StartJump_GetSpeed_FromEqualToBeforeJump_ToSpeed.
Referenced by StartJump.
float WholeVelocityWhileJumping.StartJump_GetSpeed_EqualToBeforeJump(WholeVelocityBeforeJump velocityBeforeJump, StartJump_Direction_Type type, out float lastNoZeroSpeedOut, out float deltaTimeOut)
References WholeVelocityBeforeJump.history, historyZeroCutTime.
Referenced by Out_GetSpeed_EqualToBeforeJump, StartJump_GetSpeed.
float WholeVelocityWhileJumping.StartJump_GetSpeed_FromEqualToBeforeJump_ToSpeed(float speedEqualToBeforeJump, StartJump_Direction_Type type)
References wholeFistSpeedRatio.
Referenced by StartJump_GetSpeed.
void WholeVelocityWhileJumping.StartJump_SpeedAddedWhenSlanting()
References direction, jumpSpeedAddedWhenSlanting, Velocity.speed, Velocity.velocity.
Referenced by StartJump.
Vector2 StartJump_Direction_Type type WholeVelocityWhileJumping.Out_GetDirection(WholeVelocityBeforeJump velocityBeforeJump)
References StartJump_GetDirection.
Referenced by PlayerControl.BodyArrowRepresent.