Shapes2D::ShapeEditor
SerializedProperty Shapes2D.ShapeEditor.shapeTypeProp
Referenced by Shapes2D.ShapeEditor.OnEnable, Shapes2D.ShapeEditor.OnInspectorGUI.
SerializedProperty Shapes2D.ShapeEditor.outlineSizeProp
Referenced by Shapes2D.ShapeEditor.OnEnable, Shapes2D.ShapeEditor.OnInspectorGUI.
SerializedProperty Shapes2D.ShapeEditor.blurProp
Referenced by Shapes2D.ShapeEditor.OnEnable, Shapes2D.ShapeEditor.OnInspectorGUI.
SerializedProperty Shapes2D.ShapeEditor.outlineColorProp
Referenced by Shapes2D.ShapeEditor.OnEnable, Shapes2D.ShapeEditor.OnInspectorGUI.
SerializedProperty Shapes2D.ShapeEditor.fillTypeProp
Referenced by Shapes2D.ShapeEditor.OnEnable, Shapes2D.ShapeEditor.OnInspectorGUI.
SerializedProperty Shapes2D.ShapeEditor.fillColorProp
Referenced by Shapes2D.ShapeEditor.OnEnable, Shapes2D.ShapeEditor.OnInspectorGUI.
SerializedProperty Shapes2D.ShapeEditor.fillColor2Prop
Referenced by Shapes2D.ShapeEditor.OnEnable, Shapes2D.ShapeEditor.OnInspectorGUI.
SerializedProperty Shapes2D.ShapeEditor.gradientTypeProp
Referenced by Shapes2D.ShapeEditor.OnEnable, Shapes2D.ShapeEditor.OnInspectorGUI.
SerializedProperty Shapes2D.ShapeEditor.roundnessProp
Referenced by Shapes2D.ShapeEditor.OnEnable, Shapes2D.ShapeEditor.OnInspectorGUI.
SerializedProperty Shapes2D.ShapeEditor.roundnessTLProp
Referenced by Shapes2D.ShapeEditor.OnEnable, Shapes2D.ShapeEditor.OnInspectorGUI.
SerializedProperty Shapes2D.ShapeEditor.roundnessTRProp
Referenced by Shapes2D.ShapeEditor.OnEnable, Shapes2D.ShapeEditor.OnInspectorGUI.
SerializedProperty Shapes2D.ShapeEditor.roundnessBLProp
Referenced by Shapes2D.ShapeEditor.OnEnable, Shapes2D.ShapeEditor.OnInspectorGUI.
SerializedProperty Shapes2D.ShapeEditor.roundnessBRProp
Referenced by Shapes2D.ShapeEditor.OnEnable, Shapes2D.ShapeEditor.OnInspectorGUI.
SerializedProperty Shapes2D.ShapeEditor.roundnessPerCornerProp
Referenced by Shapes2D.ShapeEditor.OnEnable, Shapes2D.ShapeEditor.OnInspectorGUI.
SerializedProperty Shapes2D.ShapeEditor.fillRotationProp
Referenced by Shapes2D.ShapeEditor.OnEnable, Shapes2D.ShapeEditor.OnInspectorGUI.
SerializedProperty Shapes2D.ShapeEditor.fillOffsetProp
Referenced by Shapes2D.ShapeEditor.OnEnable, Shapes2D.ShapeEditor.OnInspectorGUI.
SerializedProperty Shapes2D.ShapeEditor.gradientStartProp
Referenced by Shapes2D.ShapeEditor.OnEnable, Shapes2D.ShapeEditor.OnInspectorGUI.
SerializedProperty Shapes2D.ShapeEditor.fillTextureProp
Referenced by Shapes2D.ShapeEditor.OnEnable, Shapes2D.ShapeEditor.OnInspectorGUI.
SerializedProperty Shapes2D.ShapeEditor.gridSizeProp
Referenced by Shapes2D.ShapeEditor.OnEnable, Shapes2D.ShapeEditor.OnInspectorGUI.
SerializedProperty Shapes2D.ShapeEditor.lineSizeProp
Referenced by Shapes2D.ShapeEditor.OnEnable, Shapes2D.ShapeEditor.OnInspectorGUI.
SerializedProperty Shapes2D.ShapeEditor.triangleOffsetProp
Referenced by Shapes2D.ShapeEditor.OnEnable, Shapes2D.ShapeEditor.OnInspectorGUI.
SerializedProperty Shapes2D.ShapeEditor.fillScaleProp
Referenced by Shapes2D.ShapeEditor.OnEnable, Shapes2D.ShapeEditor.OnInspectorGUI.
SerializedProperty Shapes2D.ShapeEditor.gradientAxisProp
Referenced by Shapes2D.ShapeEditor.OnEnable, Shapes2D.ShapeEditor.OnInspectorGUI.
SerializedProperty Shapes2D.ShapeEditor.polygonPresetProp
Referenced by Shapes2D.ShapeEditor.OnEnable, Shapes2D.ShapeEditor.OnInspectorGUI.
SerializedProperty Shapes2D.ShapeEditor.usePolygonMapProp
Referenced by Shapes2D.ShapeEditor.OnEnable, Shapes2D.ShapeEditor.OnInspectorGUI.
SerializedProperty Shapes2D.ShapeEditor.startAngleProp
Referenced by Shapes2D.ShapeEditor.OnEnable, Shapes2D.ShapeEditor.OnInspectorGUI.
SerializedProperty Shapes2D.ShapeEditor.endAngleProp
Referenced by Shapes2D.ShapeEditor.OnEnable, Shapes2D.ShapeEditor.OnInspectorGUI.
SerializedProperty Shapes2D.ShapeEditor.invertArcProp
Referenced by Shapes2D.ShapeEditor.OnEnable, Shapes2D.ShapeEditor.OnInspectorGUI.
SerializedProperty Shapes2D.ShapeEditor.innerCutoutProp
Referenced by Shapes2D.ShapeEditor.OnEnable, Shapes2D.ShapeEditor.OnInspectorGUI.
SerializedProperty Shapes2D.ShapeEditor.pathThicknessProp
Referenced by Shapes2D.ShapeEditor.OnEnable, Shapes2D.ShapeEditor.OnInspectorGUI.
SerializedProperty Shapes2D.ShapeEditor.fillPathLoopsProp
Referenced by Shapes2D.ShapeEditor.OnEnable, Shapes2D.ShapeEditor.OnInspectorGUI.
bool Shapes2D.ShapeEditor.isEditing
Referenced by Shapes2D.ShapeEditor.EditShape, Shapes2D.ShapeEditor.OnInspectorGUI, Shapes2D.ShapeEditor.OnSceneGUI, Shapes2D.ShapeEditor.StopEditingShape.
Tool Shapes2D.ShapeEditor.preEditTool
Referenced by Shapes2D.ShapeEditor.EditShape, Shapes2D.ShapeEditor.StopEditingShape.
void Shapes2D.ShapeEditor.OnEnable()
References Shapes2D.ShapeEditor.blurProp, Shapes2D.ShapeEditor.endAngleProp, Shapes2D.ShapeEditor.fillColor2Prop, Shapes2D.ShapeEditor.fillColorProp, Shapes2D.ShapeEditor.fillOffsetProp, Shapes2D.ShapeEditor.fillPathLoopsProp, Shapes2D.ShapeEditor.fillRotationProp, Shapes2D.ShapeEditor.fillScaleProp, Shapes2D.ShapeEditor.fillTextureProp, Shapes2D.ShapeEditor.fillTypeProp, Shapes2D.ShapeEditor.gradientAxisProp, Shapes2D.ShapeEditor.gradientStartProp, Shapes2D.ShapeEditor.gradientTypeProp, Shapes2D.ShapeEditor.gridSizeProp, Shapes2D.ShapeEditor.innerCutoutProp, Shapes2D.ShapeEditor.invertArcProp, Shapes2D.ShapeEditor.lineSizeProp, Shapes2D.ShapeEditor.outlineColorProp, Shapes2D.ShapeEditor.outlineSizeProp, Shapes2D.ShapeEditor.pathThicknessProp, Shapes2D.ShapeEditor.polygonPresetProp, Shapes2D.ShapeEditor.roundnessBLProp, Shapes2D.ShapeEditor.roundnessBRProp, Shapes2D.ShapeEditor.roundnessPerCornerProp, Shapes2D.ShapeEditor.roundnessProp, Shapes2D.ShapeEditor.roundnessTLProp, Shapes2D.ShapeEditor.roundnessTRProp, Shapes2D.ShapeEditor.shapeTypeProp, Shapes2D.ShapeEditor.startAngleProp, Shapes2D.ShapeEditor.triangleOffsetProp, Shapes2D.ShapeEditor.usePolygonMapProp.
void Shapes2D.ShapeEditor.EditShape()
References Shapes2D.ShapeEditor.isEditing, Shapes2D.ShapeEditor.preEditTool.
Referenced by Shapes2D.ShapeEditor.OnInspectorGUI.
void Shapes2D.ShapeEditor.StopEditingShape(bool restoreTool)
References Shapes2D.ShapeEditor.isEditing, Shapes2D.ShapeEditor.preEditTool.
Referenced by Shapes2D.ShapeEditor.EditPath, Shapes2D.ShapeEditor.EditPolygon, Shapes2D.ShapeEditor.OnInspectorGUI, Shapes2D.ShapeEditor.OnSceneGUI.
int Shapes2D.ShapeEditor.GetClosestLineToPoint(Vector3 pos, List< Vector3 > verts)
Referenced by Shapes2D.ShapeEditor.EditPolygon.
void Shapes2D.ShapeEditor.DrawShapeBorders(Shape shape)
Referenced by Shapes2D.ShapeEditor.OnSceneGUI.
Vector3 Shapes2D.ShapeEditor.GetMouseWorldPos()
Referenced by Shapes2D.ShapeEditor.EditPath.
void Shapes2D.ShapeEditor.EditPolygon(Shape shape)
References Shapes2D.ShapeEditor.GetClosestLineToPoint, Shapes2D.ShapeEditor.StopEditingShape.
Referenced by Shapes2D.ShapeEditor.OnSceneGUI.
void Shapes2D.ShapeEditor.DoMovePathPoint(List< PathSegment > segments, int i, Vector2 newPos)
Referenced by Shapes2D.ShapeEditor.MovePathPoint, Shapes2D.ShapeEditor.MovePathPointsAtPosition.
void Shapes2D.ShapeEditor.MovePathPointsAtPosition(List< PathSegment > segments, Vector2 oldPos, Vector2 newPos)
References Shapes2D.ShapeEditor.DoMovePathPoint.
Referenced by Shapes2D.ShapeEditor.MovePathPoint.
void Shapes2D.ShapeEditor.MovePathPoint(List< PathSegment > segments, int i, Vector3 newPos, bool moveConnected=true)
References Shapes2D.ShapeEditor.DoMovePathPoint, Shapes2D.ShapeEditor.MovePathPointsAtPosition.
Referenced by Shapes2D.ShapeEditor.EditPath.
void Shapes2D.ShapeEditor.EditPath(Shape shape)
References Shapes2D.ShapeEditor.GetMouseWorldPos, Shapes2D.ShapeEditor.MovePathPoint, Shapes2D.ShapeEditor.StopEditingShape.
Referenced by Shapes2D.ShapeEditor.OnSceneGUI.
void Shapes2D.ShapeEditor.OnSceneGUI()
References Shapes2D.ShapeEditor.DrawShapeBorders, Shapes2D.ShapeEditor.EditPath, Shapes2D.ShapeEditor.EditPolygon, Shapes2D.ShapeEditor.isEditing, Shapes2D.ShapeEditor.StopEditingShape.
Shapes2DPrefs Shapes2D.ShapeEditor.GetPreferences()
Referenced by Shapes2D.ShapeEditor.ConvertToSprite.
void Shapes2D.ShapeEditor.SetPolygonCollider2D(Shape shape)
Referenced by Shapes2D.ShapeEditor.OnInspectorGUI.
void Shapes2D.ShapeEditor.FromPolygonCollider2D(Shape shape)
Referenced by Shapes2D.ShapeEditor.OnInspectorGUI.
void Shapes2D.ShapeEditor.ConvertToSprite(Shape shape)
References Shapes2D.ShapeEditor.GetDefaultSpriteMaterial, Shapes2D.ShapeEditor.GetPreferences, Shapes2D.ShapeEditor.RenderToTexture2D.
Referenced by Shapes2D.ShapeEditor.OnInspectorGUI.
static Color Shapes2D.ShapeEditor.BlendColors(Color dst, Color src)
Referenced by Shapes2D.ShapeEditor.BlendTextures.
static void Shapes2D.ShapeEditor.BlendTextures(Texture2D dstTex, Texture2D srcTex)
References Shapes2D.ShapeEditor.BlendColors.
Referenced by Shapes2D.ShapeEditor.RenderToTexture2D.
static List<GraphicState> Shapes2D.ShapeEditor.DisableUIGraphics(Canvas canvas)
References Shapes2D.ShapeEditor.GraphicState.hasMask.
Referenced by Shapes2D.ShapeEditor.RenderToTexture2D.
static Vector2 Shapes2D.ShapeEditor.RenderToTexture2D(string path, Shape shape, float pixelsPerUnit=100)
References Shapes2D.ShapeEditor.BlendTextures, Shapes2D.ShapeEditor.DisableUIGraphics, Shapes2D.ShapeEditor.GraphicState.graphic, Shapes2D.ShapeEditor.GraphicState.hasMask, Shapes2D.ShapeEditor.GraphicState.showMaskGraphic.
Referenced by Shapes2D.ShapeEditor.ConvertToSprite.
static Material Shapes2D.ShapeEditor.GetDefaultSpriteMaterial()
Referenced by Shapes2D.ShapeEditor.ConvertToSprite.
override void Shapes2D.ShapeEditor.OnInspectorGUI()
References Shapes2D.ShapeEditor.blurProp, Shapes2D.ShapeEditor.ConvertToSprite, Shapes2D.ShapeEditor.EditShape, Shapes2D.ShapeEditor.endAngleProp, Shapes2D.ShapeEditor.fillColor2Prop, Shapes2D.ShapeEditor.fillColorProp, Shapes2D.ShapeEditor.fillOffsetProp, Shapes2D.ShapeEditor.fillPathLoopsProp, Shapes2D.ShapeEditor.fillRotationProp, Shapes2D.ShapeEditor.fillScaleProp, Shapes2D.ShapeEditor.fillTextureProp, Shapes2D.ShapeEditor.fillTypeProp, Shapes2D.ShapeEditor.FromPolygonCollider2D, Shapes2D.ShapeEditor.gradientAxisProp, Shapes2D.ShapeEditor.gradientStartProp, Shapes2D.ShapeEditor.gradientTypeProp, Shapes2D.ShapeEditor.gridSizeProp, Shapes2D.ShapeEditor.innerCutoutProp, Shapes2D.ShapeEditor.invertArcProp, Shapes2D.ShapeEditor.isEditing, Shapes2D.ShapeEditor.lineSizeProp, Shapes2D.ShapeEditor.outlineColorProp, Shapes2D.ShapeEditor.outlineSizeProp, Shapes2D.ShapeEditor.pathThicknessProp, Shapes2D.ShapeEditor.polygonPresetProp, Shapes2D.ShapeEditor.roundnessBLProp, Shapes2D.ShapeEditor.roundnessBRProp, Shapes2D.ShapeEditor.roundnessPerCornerProp, Shapes2D.ShapeEditor.roundnessProp, Shapes2D.ShapeEditor.roundnessTLProp, Shapes2D.ShapeEditor.roundnessTRProp, Shapes2D.ShapeEditor.SetPolygonCollider2D, Shapes2D.ShapeEditor.shapeTypeProp, Shapes2D.ShapeEditor.startAngleProp, Shapes2D.ShapeEditor.StopEditingShape, Shapes2D.ShapeEditor.triangleOffsetProp, Shapes2D.ShapeEditor.usePolygonMapProp.