Y::SetCommands
Dictionary<string, Func<string[], IEnumerator> > Y.SetCommands.sublogics
Referenced by Y.SetCommands.Execute, Y.SetCommands.SetCommands.
Vector2Int Y.SetCommands.defaultResolution
Referenced by Y.SetCommands.SetCommands.
override string Y.SetCommands.Help()
References Y.SetCommands.GetName.
Y.SetCommands.SetCommands()
References Y.SetCommands.defaultResolution, Y.SetCommands.SetFramerate, Y.SetCommands.SetResolution, Y.SetCommands.sublogics.
override IEnumerator Y.SetCommands.Execute(params string[] args)
References Y.SetCommands.sublogics.
override string Y.SetCommands.GetName()
Referenced by Y.SetCommands.Help.
IEnumerator Y.SetCommands.SetResolution(params string[] args)
Referenced by Y.SetCommands.SetCommands.
IEnumerator Y.SetCommands.SetFramerate(params string[] args)
Referenced by Y.SetCommands.SetCommands.