AABBUtilities
float AABBUtilities.leftSaved
Referenced by Restore, Save.
float AABBUtilities.rightSaved
Referenced by Restore, Save.
float AABBUtilities.bottomSaved
Referenced by Restore, Save.
float AABBUtilities.topSaved
Referenced by Restore, Save.
float AABBUtilities.scaleXSaved
Referenced by RestoreScaleX, SaveScaleX.
float AABBUtilities.scaleYSaved
Referenced by RestoreScaleY, SaveScaleY.
static void AABBUtilities.PrintAABB()
static void AABBUtilities.SaveLeft()
References Save.
Referenced by MaintainLeftBottomSacleX_Start, MaintainTopLeftSacleY_Start.
static void AABBUtilities.SaveRight()
References Save.
static void AABBUtilities.SaveBottom()
References Save.
Referenced by MaintainLeftBottomSacleX_Start.
static void AABBUtilities.SaveTop()
References Save.
Referenced by MaintainTopLeftSacleY_Start.
static void AABBUtilities.Save(string which)
References bottomSaved, leftSaved, rightSaved, topSaved.
Referenced by SaveBottom, SaveLeft, SaveRight, SaveTop.
static void AABBUtilities.RestoreLeft()
References Restore.
Referenced by MaintainLeftBottomSacleX_End, MaintainTopLeftSacleY_End.
static void AABBUtilities.RestoreRight()
References Restore.
static void AABBUtilities.RestoreBottom()
References Restore.
Referenced by MaintainLeftBottomSacleX_End.
static void AABBUtilities.RestoreTop()
References Restore.
Referenced by MaintainTopLeftSacleY_End.
static void AABBUtilities.Restore(string which)
References bottomSaved, leftSaved, rightSaved, topSaved.
Referenced by RestoreBottom, RestoreLeft, RestoreRight, RestoreTop.
static void AABBUtilities.SaveScaleX()
References scaleXSaved.
Referenced by MaintainLeftBottomSacleX_Start.
static void AABBUtilities.SaveScaleY()
References scaleYSaved.
Referenced by MaintainTopLeftSacleY_Start.
static void AABBUtilities.RestoreScaleX()
References scaleXSaved.
Referenced by MaintainLeftBottomSacleX_End.
static void AABBUtilities.RestoreScaleY()
References scaleYSaved.
Referenced by MaintainTopLeftSacleY_End.
static void AABBUtilities.MaintainTopLeftSacleY_Start()
References SaveLeft, SaveScaleY, SaveTop.
static void AABBUtilities.MaintainTopLeftSacleY_End()
References RestoreLeft, RestoreScaleY, RestoreTop.
static void AABBUtilities.MaintainLeftBottomSacleX_Start()
References SaveBottom, SaveLeft, SaveScaleX.
static void AABBUtilities.MaintainLeftBottomSacleX_End()
References RestoreBottom, RestoreLeft, RestoreScaleX.