Shapes2D::Bird
Rigidbody2D Shapes2D.Bird.rb
Referenced by Shapes2D.Bird.Flap, Shapes2D.Bird.Start.
bool Shapes2D.Bird.dead
Referenced by Shapes2D.Bird.Die, Shapes2D.Bird.IsDead, Shapes2D.Bird.Play, Shapes2D.Bird.Reset.
bool Shapes2D.Bird.playing
Referenced by Shapes2D.Bird.Die, Shapes2D.Bird.IsPlaying, Shapes2D.Bird.Play, Shapes2D.Bird.Reset, Shapes2D.Bird.Update.
Vector3 Shapes2D.Bird.startPosition
Referenced by Shapes2D.Bird.Reset, Shapes2D.Bird.Start.
int Shapes2D.Bird.score
Referenced by Shapes2D.Bird.GetScore, Shapes2D.Bird.OnTriggerEnter2D, Shapes2D.Bird.Reset.
float Shapes2D.Bird.force
Referenced by Shapes2D.Bird.Die, Shapes2D.Bird.Flap.
void Shapes2D.Bird.Start()
References Shapes2D.Bird.rb, Shapes2D.Bird.Reset, Shapes2D.Bird.startPosition.
void Shapes2D.Bird.OnTriggerEnter2D(Collider2D other)
References Shapes2D.Bird.Die, Shapes2D.Bird.score.
void Shapes2D.Bird.OnCollisionEnter2D(Collision2D coll)
References Shapes2D.Bird.Die.
void Shapes2D.Bird.Die()
References Shapes2D.Bird.dead, Shapes2D.Bird.force, Shapes2D.Bird.playing.
Referenced by Shapes2D.Bird.OnCollisionEnter2D, Shapes2D.Bird.OnTriggerEnter2D.
void Shapes2D.Bird.Flap()
References Shapes2D.Bird.force, Shapes2D.Bird.rb.
Referenced by Shapes2D.Bird.Play, Shapes2D.Bird.Update.
void Shapes2D.Bird.Update()
References Shapes2D.Bird.Flap, Shapes2D.InputUtils.MouseDownOrTap, Shapes2D.Bird.playing.
int Shapes2D.Bird.GetScore()
References Shapes2D.Bird.score.
bool Shapes2D.Bird.IsDead()
References Shapes2D.Bird.dead.
Referenced by Shapes2D.Game.OnStartButton, Shapes2D.Game.Update.
void Shapes2D.Bird.Reset()
References Shapes2D.Bird.dead, Shapes2D.Bird.playing, Shapes2D.Bird.score, Shapes2D.Bird.startPosition.
Referenced by Shapes2D.Bird.Play, Shapes2D.Bird.Start.
bool Shapes2D.Bird.IsPlaying()
References Shapes2D.Bird.playing.
Referenced by Shapes2D.Game.OnStartButton, Shapes2D.Game.Update.
void Shapes2D.Bird.Play()
References Shapes2D.Bird.dead, Shapes2D.Bird.Flap, Shapes2D.Bird.playing, Shapes2D.Bird.Reset.