PlayerControl
PlayerControl PlayerControl.playerControl
Referenced by Awake, Stuff.Sword.CheckAndRemoveFist, EasyDebug.FixedUpdate, LevelManager.GameRestartCoroutine, LevelManager.PlayerDiePre, PlayerControlStaticSetting.SetMoveDirectionReverseIfGrabEnv, Win.Start.
float PlayerControl.footState_surfaceUpDownOffset
Referenced by Init.
float PlayerControl.footState_surfaceLeftRightInaccuracy
Referenced by Init.
int PlayerControl.moveDirectionReverseIfGrabEnv
Referenced by FU_FistOffetInfluenceSpeed, FU_FistSpeed, Init, Out_GetMoveDirectionReverseIfGrabEnv, Out_SetMoveDirectionReverseIfGrabEnv.
bool PlayerControl.jumpSpeedAddedWhenSlanting
Referenced by Init.
float PlayerControl.wholeJumpSpeedHistoryTime
Referenced by CheckSetting, Init.
float PlayerControl.wholeJumpSpeedZeroCutTime
Referenced by CheckSetting, Init.
float PlayerControl.wholeJumpSpeedSimpleDirectionTime
Referenced by CheckSetting, Init.
float PlayerControl.wholeJumpSpeedComplexDirectionTime
Referenced by Init.
float PlayerControl.wholeSpeedDownPartMax
Referenced by Init.
float PlayerControl.wholeFistSpeedRatio
Referenced by Init.
float PlayerControl.gravity
Referenced by Init.
float PlayerControl.friction
Referenced by Init.
GameObject PlayerControl.whole
Referenced by Init.
GameObject PlayerControl.bottomLeftPoint
Referenced by FU_Pre, Init.
GameObject PlayerControl.bottomMiddlePoint
Referenced by Init.
GameObject PlayerControl.bottomRightPoint
Referenced by FU_Pre, Init.
GameObject PlayerControl.arrowSign
Referenced by Init.
HandRepresent PlayerControl.handRepresent
Referenced by Init.
FistStatePlus PlayerControl.leftFistState
Referenced by FistRepresent, FixedUpdate, FU_FistOffetInfluenceSpeed, FU_FistSpeed, FU_Pre, FU_Whole_Velocity, HandStuffFixedUpdate, YDebugPanelShow_FUPre.
FistStatePlus PlayerControl.rightFistState
Referenced by FistRepresent, FixedUpdate, FU_FistOffetInfluenceSpeed, FU_FistSpeed, FU_Pre, FU_Whole_Velocity, HandStuffFixedUpdate, YDebugPanelShow_FUPre.
GameObject PlayerControl.leftGrabedStuff
Referenced by FistRepresent, ForSword_UnSetGrabedStuff, FU_Pre, HandStuffFixedUpdate.
GameObject PlayerControl.rightGrabedStuff
Referenced by FistRepresent, ForSword_UnSetGrabedStuff, FU_Pre, HandStuffFixedUpdate.
FootStatePlus PlayerControl.footState
Referenced by FU_Whole_Offset, FU_Whole_Velocity, Init, YDebugPanelShow_FUPre.
TwoFistVelocity PlayerControl.fistVelocity
Referenced by FU_FistOffset, Init.
FistVelocity PlayerControl.leftFistVelocity
Referenced by Init.
FistVelocity PlayerControl.rightFistVelocity
Referenced by Init.
TwoFistOffset PlayerControl.fistOffset
Referenced by FU_Fist, Init.
WholeVelocityBeforeJump PlayerControl.wholeVelocityBeforeJump
Referenced by BodyArrowRepresent, FU_Whole_Velocity, Init.
WholeVelocityWhileJumping PlayerControl.wholeVelocityWhileJumping
Referenced by BodyArrowRepresent, Init.
WholeOffset PlayerControl.wholeOffset
Referenced by FU_Whole, FU_Whole_Velocity, Init.
float PlayerControl.length
Referenced by FU_FistOffset, Init, YDebugPanelShow_Init.
SpriteRenderer PlayerControl.normalColorRender
Referenced by Init.
SpriteRenderer PlayerControl.pressedColorRender
Referenced by Init.
GameObject PlayerControl.leftFist
Referenced by FistRepresent, ForSword_CheckOverlap, ForSword_GiveValue, FU_Pre, FU_Whole_Offset, HandStuffFixedUpdate, Init.
GameObject PlayerControl.rightFist
Referenced by FistRepresent, ForSword_CheckOverlap, ForSword_GiveValue, FU_Pre, FU_Whole_Offset, HandStuffFixedUpdate, Init.
HandControlFade PlayerControl.handFade
Referenced by Init.
HCAudio PlayerControl.hcAudio
Referenced by Init.
WholeState PlayerControl.wholeState
Referenced by BodyArrowRepresent, EasyDebug.FixedUpdate, FU_Whole_Velocity.
void PlayerControl.Awake()
References playerControl.
void PlayerControl.Start()
References Init.
void PlayerControl.Init()
References arrowSign, bottomLeftPoint, bottomMiddlePoint, bottomRightPoint, CheckSetting, fistOffset, fistVelocity, footState, footState_surfaceLeftRightInaccuracy, footState_surfaceUpDownOffset, friction, gravity, handFade, handRepresent, hcAudio, jumpSpeedAddedWhenSlanting, leftFist, leftFistVelocity, length, moveDirectionReverseIfGrabEnv, normalColorRender, pressedColorRender, rightFist, rightFistVelocity, whole, wholeFistSpeedRatio, wholeJumpSpeedComplexDirectionTime, wholeJumpSpeedHistoryTime, wholeJumpSpeedSimpleDirectionTime, wholeJumpSpeedZeroCutTime, wholeOffset, wholeSpeedDownPartMax, wholeVelocityBeforeJump, wholeVelocityWhileJumping, YDebugPanelShow_Init.
Referenced by Start.
void PlayerControl.CheckSetting()
References wholeJumpSpeedHistoryTime, wholeJumpSpeedSimpleDirectionTime, wholeJumpSpeedZeroCutTime.
Referenced by Init.
void PlayerControl.YDebugPanelShow_Init()
References length.
Referenced by Init.
void PlayerControl.FixedUpdate()
References FU_Main, FU_Pre, FU_Represent, leftFistState, rightFistState.
void PlayerControl.FU_Main()
References FU_Fist, FU_Whole.
Referenced by FixedUpdate.
void PlayerControl.FU_Fist()
References fistOffset, FU_FistOffetInfluenceSpeed, FU_FistOffset, FU_FistSpeed, TwoFistOffset.left.
Referenced by FU_Main.
void PlayerControl.FU_FistSpeed()
References FistGrabStuffEnvHelper, HKey.lAnyDirKeyHold, leftFistState, HKey.lMvDir, moveDirectionReverseIfGrabEnv, HKey.rAnyDirKeyHold, rightFistState, HKey.rMvDir.
Referenced by FU_Fist.
void PlayerControl.FU_FistOffset()
References Velocity.direction, FistGrabStuffEnvHelper, fistVelocity, TwoFistVelocity.left, length, TwoFistVelocity.right.
Referenced by FU_Fist.
void PlayerControl.FU_FistOffetInfluenceSpeed()
References FistGrabStuffEnvHelper, HKey.lAnyDirKeyHold, leftFistState, HKey.lMvDir, moveDirectionReverseIfGrabEnv, HKey.rAnyDirKeyHold, rightFistState, HKey.rMvDir.
Referenced by FU_Fist.
void PlayerControl.FistGrabStuffEnvHelper(ref FistState leftFistStateTemp, ref FistState rightFistStateTemp)
References GrabEnv, GrabStuff.
Referenced by FU_FistOffetInfluenceSpeed, FU_FistOffset, FU_FistSpeed, FU_Whole_Offset, FU_Whole_Velocity.
void PlayerControl.FU_Whole()
References FU_Whole_Offset, FU_Whole_Velocity, WholeOffset.offset, wholeOffset.
Referenced by FU_Main.
void PlayerControl.FU_Whole_Velocity()
References BeforeJump, FistGrabStuffEnvHelper, footState, leftFistState, rightFistState, WhileJumping, wholeOffset, wholeState, wholeVelocityBeforeJump.
Referenced by FU_Whole.
void PlayerControl.FU_Whole_Offset()
References FistGrabStuffEnvHelper, footState, leftFist, rightFist.
Referenced by FU_Whole.
void PlayerControl.___________________________()
void PlayerControl.FU_Pre()
References bottomLeftPoint, bottomRightPoint, HandStuffFixedUpdate, leftFist, leftFistState, leftGrabedStuff, HKey.lGrab, FistStatePlus.pre, HKey.rGrab, rightFist, rightFistState, rightGrabedStuff, YDebugPanelShow_FUPre.
Referenced by FixedUpdate.
void PlayerControl.HandStuffFixedUpdate(FistState rightPre, FistState leftPre)
References leftFist, leftFistState, leftGrabedStuff, HKey.lMvDir, rightFist, rightFistState, rightGrabedStuff, HKey.rMvDir.
Referenced by FU_Pre.
void PlayerControl.YDebugPanelShow_FUPre()
References footState, leftFistState, rightFistState.
Referenced by FU_Pre.
void PlayerControl.FU_Represent()
References BodyArrowRepresent, FistRepresent.
Referenced by FixedUpdate.
void PlayerControl.FistRepresent()
References GrabEnv, FistStatePlus.IsGrabPressed, leftFist, leftFistState, leftGrabedStuff, rightFist, rightFistState, rightGrabedStuff.
Referenced by FU_Represent.
void PlayerControl.BodyArrowRepresent()
References Velocity.direction, GetGreenYellowRedGraduallyColor, WholeVelocityWhileJumping.Out_GetDirection, SetArrowColor, wholeState, wholeVelocityBeforeJump, wholeVelocityWhileJumping.
Referenced by FU_Represent.
void PlayerControl.SetArrowColor(Color c)
Referenced by BodyArrowRepresent.
Color PlayerControl.GetGreenYellowRedGraduallyColor(float x)
Referenced by BodyArrowRepresent.
void PlayerControl.Update()
ValueForSword PlayerControl.ForSword_GiveValue(string fist)
References leftFist, rightFist.
bool PlayerControl.ForSword_CheckOverlap(string fist, GameObject stuffObject)
References leftFist, rightFist.
Referenced by Stuff.Sword.CheckAndRemoveFist.
void PlayerControl.ForSword_UnSetGrabedStuff(string fist)
References leftGrabedStuff, rightGrabedStuff.
void PlayerControl.Out_SetMoveDirectionReverseIfGrabEnv(int value)
References moveDirectionReverseIfGrabEnv.
int PlayerControl.Out_GetMoveDirectionReverseIfGrabEnv()
References moveDirectionReverseIfGrabEnv.