Stuff::Sword
State
WithHandState
NoHandState
List<Sword> Stuff.Sword.instanceList
Rigidbody2D Stuff.Sword.swordRigid
Referenced by Stuff.Sword.Start.
float Stuff.Sword.angleSpeed
Referenced by Stuff.Sword.Motion_HandAndFree_Rotation.
float Stuff.Sword.toHolderPositionSpeed
Referenced by Stuff.Sword.Motion_HandAndFree_Position.
GameObject Stuff.Sword.tip
Referenced by Stuff.Sword.GetValueForFist_AtFUPre, Stuff.Sword.Motion_NoHand_AdjustDirection, Stuff.Sword.Motion_NoHand_Env, Stuff.Sword.Motion_NoHand_OutOfCameraRegion, Stuff.Sword.Start, Stuff.Sword.StateRenewDueToFistAndEnv.
Collider2D Stuff.Sword.tipEnvCollider
Referenced by Stuff.Sword.Start, Stuff.Sword.Visual.
GameObject Stuff.Sword.tipEnvVisual
Referenced by Stuff.Sword.Start.
GameObject Stuff.Sword.body
Referenced by Stuff.Sword.GetValueForFist_AtFUPre, Stuff.Sword.Motion_NoHand_AdjustDirection, Stuff.Sword.Motion_NoHand_Env, Stuff.Sword.Start, Stuff.Sword.StateRenewDueToFistAndEnv.
Transform Stuff.Sword.rayPoint1
Referenced by Stuff.Sword.Start.
Transform Stuff.Sword.rayPoint2
Referenced by Stuff.Sword.Start.
Transform Stuff.Sword.rayPoint3
Referenced by Stuff.Sword.Start.
Transform Stuff.Sword.centerPoint
Referenced by Stuff.Sword.Start.
List<Collider2D> Stuff.Sword.bodyEnvColliderList
Referenced by Stuff.Sword.Start, Stuff.Sword.Visual.
List<GameObject> Stuff.Sword.bodyEnvVisualList
Referenced by Stuff.Sword.Start, Stuff.Sword.Visual.
GameObject Stuff.Sword.gem
Referenced by Stuff.Sword.Start.
GameObject Stuff.Sword.freeSign
Referenced by Stuff.Sword.Start.
GameObject Stuff.Sword.holdPosition
Referenced by Stuff.Sword.Motion_HandAndFree_Position, Stuff.Sword.Start.
Vector3 Stuff.Sword.startingPosition
Referenced by Stuff.Sword.Start.
Quaternion Stuff.Sword.startingRotation
Referenced by Stuff.Sword.Start.
StatePack Stuff.Sword.states
Referenced by Stuff.Sword.Motion, Stuff.Sword.Motion_HandAndFree_Rotation, Stuff.Sword.Motion_NoHand, Stuff.Sword.Motion_NoHand_Env, Stuff.Sword.SoundEffect, Stuff.Sword.Start, Stuff.Sword.ThrowSword, Stuff.Sword.Visual.
Vector2 Stuff.Sword.handAndFree_LastNonZeroHandOffset
Referenced by Stuff.Sword.Motion_HandAndFree_Rotation.
float Stuff.Sword.noHand_speed
Referenced by Stuff.Sword.Motion_NoHand_Dropping, Stuff.Sword.Motion_NoHand_Env, Stuff.Sword.Motion_NoHand_Flying, Stuff.Sword.Start, Stuff.Sword.ThrowSword.
Vector2 Stuff.Sword.noHand_direction
Referenced by Stuff.Sword.Motion_NoHand_AdjustDirection, Stuff.Sword.Motion_NoHand_Dropping, Stuff.Sword.Motion_NoHand_Env, Stuff.Sword.Motion_NoHand_Flying, Stuff.Sword.Motion_NoHand_OutOfCameraRegion, Stuff.Sword.Start, Stuff.Sword.ThrowSword.
List<Vector2> Stuff.Sword.handAndFreeOffsetHistory
Referenced by Stuff.Sword.SoundEffect, Stuff.Sword.Start.
const float Stuff.Sword.noHand_stopedAngleSpeed
Referenced by Stuff.Sword.Motion_NoHand_Env.
const float Stuff.Sword.noHand_swordFly_fistToSwordSpeedRatio
Referenced by Stuff.Sword.ThrowSword.
const float Stuff.Sword.noHand_swordFly_minSpeed
Referenced by Stuff.Sword.Motion_NoHand_Flying.
const float Stuff.Sword.noHand_swordFly_deceleration
Referenced by Stuff.Sword.Motion_NoHand_Dropping, Stuff.Sword.Motion_NoHand_Flying.
const float Stuff.Sword.noHand_swordDrop_downMax
Referenced by Stuff.Sword.Motion_NoHand_Dropping.
const float Stuff.Sword.noHand_swordDrop_acceleration
Referenced by Stuff.Sword.Motion_NoHand_Dropping.
const float Stuff.Sword.noHandEnvSpeedThreshold
Referenced by Stuff.Sword.Motion_NoHand_Env.
const float Stuff.Sword.nohandEnvMoveDistance
Referenced by Stuff.Sword.Motion_NoHand_Env.
int Stuff.Sword.soundEffect_LastWhooshNum
Referenced by Stuff.Sword.SoundEffect.
float Stuff.Sword.soundEffect_whooshInterval
Referenced by Stuff.Sword.SoundEffect.
float Stuff.Sword.soundEffect_lastWhooshTime
Referenced by Stuff.Sword.SoundEffect.
Vector3 Stuff.Sword::position
Referenced by Stuff.Sword.Motion, Stuff.Sword.Motion_NoHand.
override void Stuff.Sword.AddAssociatedFist(string fist)
References Stuff.Stuff.fists.
override void Stuff.Sword.RemoveAssociatedFist(string fist)
References Stuff.Stuff.fists.
void Stuff.Sword.ThrowSword(float speed, HandControlTool.DirectionOf9History offsetHistoryOfNineDir)
References Stuff.Sword.Motion_NoHand_AdjustDirectionRotateByHoldPosition, Stuff.Sword.noHand_direction, Stuff.Sword.noHand_speed, Stuff.Sword.noHand_swordFly_fistToSwordSpeedRatio, Stuff.Sword.StatePack.noHandState, Stuff.Sword.states.
ValueForFist Stuff.Sword.GetValueForFist_AtFUPre()
References Stuff.Sword.body, Stuff.Sword.tip.
new void Stuff.Sword.Start()
References Stuff.Sword.body, Stuff.Sword.bodyEnvColliderList, Stuff.Sword.bodyEnvVisualList, Stuff.Sword.centerPoint, Stuff.Sword.freeSign, Stuff.Sword.gem, Stuff.Sword.handAndFreeOffsetHistory, Stuff.Sword.holdPosition, Stuff.Sword.noHand_direction, Stuff.Sword.noHand_speed, Stuff.Sword.rayPoint1, Stuff.Sword.rayPoint2, Stuff.Sword.rayPoint3, Stuff.Sword.startingPosition, Stuff.Sword.startingRotation, Stuff.Sword.states, Stuff.Sword.swordRigid, Stuff.Sword.tip, Stuff.Sword.tipEnvCollider, Stuff.Sword.tipEnvVisual.
void Stuff.Sword.FixedUpdate()
References Stuff.Sword.CheckAndRemoveFist, Stuff.Sword.Motion, Stuff.Sword.SoundEffect, Stuff.Sword.StateRenewDueToFistAndEnv, Stuff.Sword.Visual.
void Stuff.Sword.StateRenewDueToFistAndEnv()
References Stuff.Sword.body, Stuff.Stuff.firstFist, Stuff.Sword.tip.
Referenced by Stuff.Sword.FixedUpdate.
void Stuff.Sword.Visual()
References Stuff.Sword.bodyEnvColliderList, Stuff.Sword.bodyEnvVisualList, Stuff.Sword.StatePack.state, Stuff.Sword.states, Stuff.Sword.tipEnvCollider, Stuff.Sword.StatePack.withHandState.
Referenced by Stuff.Sword.FixedUpdate.
void Stuff.Sword.SoundEffect()
References Stuff.Sword.handAndFreeOffsetHistory, Stuff.Sword.soundEffect_LastWhooshNum, Stuff.Sword.soundEffect_lastWhooshTime, Stuff.Sword.soundEffect_whooshInterval, Stuff.Sword.StatePack.state, Stuff.Sword.states, Stuff.Sword.StatePack.withHandState.
Referenced by Stuff.Sword.FixedUpdate.
void Stuff.Sword.Motion()
References Stuff.Stuff.firstFist, Stuff.Sword.Motion_HandAndEnv, Stuff.Sword.Motion_HandAndFree, Stuff.Sword.Motion_NoHand, Stuff.Sword.position, Stuff.Sword.StatePack.state, Stuff.Sword.states, Stuff.Sword.StatePack.withHandState.
Referenced by Stuff.Sword.FixedUpdate.
void Stuff.Sword.CheckAndRemoveFist()
References Stuff.Stuff.firstFist, Stuff.Stuff.fists, PlayerControl.ForSword_CheckOverlap, PlayerControl.playerControl.
Referenced by Stuff.Sword.FixedUpdate.
Vector3 Quaternion rotation Stuff.Sword.Motion_HandAndFree(Vector2 handOffset, Vector2 positionOffset, GameObject fistObject)
Referenced by Stuff.Sword.Motion.
Vector3 Stuff.Sword.Motion_HandAndFree_Position(Vector2 handOffset, Vector2 positionOffset, GameObject fistObject)
References Stuff.Sword.holdPosition, Stuff.Sword.toHolderPositionSpeed.
Quaternion Stuff.Sword.Motion_HandAndFree_Rotation(Vector2 handOffset)
References Stuff.Sword.angleSpeed, Stuff.Sword.handAndFree_LastNonZeroHandOffset, Stuff.Sword.StatePack.statePre, Stuff.Sword.states, Stuff.Sword.StatePack.withHandStatePre.
Vector3 Quaternion rotation Stuff.Sword.Motion_HandAndEnv(Vector2 positionOffset)
Referenced by Stuff.Sword.Motion.
Vector3 Quaternion rotation Stuff.Sword.Motion_NoHand()
References Stuff.Sword.Motion_NoHand_AdjustDirectionRotateByCenter, Stuff.Sword.Motion_NoHand_Dropping, Stuff.Sword.Motion_NoHand_Env, Stuff.Sword.Motion_NoHand_Flying, Stuff.Sword.Motion_NoHand_OutOfCameraRegion, Stuff.Sword.StatePack.noHandState, Stuff.Sword.position, Stuff.Sword.states.
Referenced by Stuff.Sword.Motion.
Vector3 Quaternion rotation Stuff.Sword.Motion_NoHand_AdjustDirectionRotateByCenter()
References Stuff.Sword.Motion_NoHand_AdjustDirection.
Referenced by Stuff.Sword.Motion_NoHand.
Vector3 Quaternion rotation Stuff.Sword.Motion_NoHand_AdjustDirectionRotateByHoldPosition()
References Stuff.Sword.Motion_NoHand_AdjustDirection.
Referenced by Stuff.Sword.ThrowSword.
Vector3 Quaternion rotation Stuff.Sword.Motion_NoHand_AdjustDirection(string rotateBy)
References Stuff.Sword.body, Stuff.Sword.noHand_direction, Stuff.Sword.tip.
Referenced by Stuff.Sword.Motion_NoHand_AdjustDirectionRotateByCenter, Stuff.Sword.Motion_NoHand_AdjustDirectionRotateByHoldPosition.
void Stuff.Sword.Motion_NoHand_OutOfCameraRegion()
References Stuff.Sword.noHand_direction, CameraFollow.screenRatio, Stuff.Sword.tip.
Referenced by Stuff.Sword.Motion_NoHand.
bool Stuff.Sword.Motion_NoHand_RayCastEnv(ref Vector2 movement)
Referenced by Stuff.Sword.Motion_NoHand_Dropping, Stuff.Sword.Motion_NoHand_Flying.
Vector3 Quaternion rotation Stuff.Sword.Motion_NoHand_Env(Vector3 positionIn, Quaternion rotationIn)
References Stuff.Sword.body, Stuff.Sword.noHand_direction, Stuff.Sword.noHand_speed, Stuff.Sword.noHand_stopedAngleSpeed, Stuff.Sword.nohandEnvMoveDistance, Stuff.Sword.noHandEnvSpeedThreshold, Stuff.Sword.StatePack.noHandState, Stuff.Sword.states, Stuff.Sword.tip.
Referenced by Stuff.Sword.Motion_NoHand.
Vector3 Quaternion rotation Stuff.Sword.Motion_NoHand_Flying(Vector3 positionIn, Quaternion rotationIn)
References Stuff.Sword.Motion_NoHand_RayCastEnv, Stuff.Sword.noHand_direction, Stuff.Sword.noHand_speed, Stuff.Sword.noHand_swordFly_deceleration, Stuff.Sword.noHand_swordFly_minSpeed.
Referenced by Stuff.Sword.Motion_NoHand.
Vector3 Quaternion rotation Stuff.Sword.Motion_NoHand_Dropping(Vector3 positionIn, Quaternion rotationIn)
References Stuff.Sword.Motion_NoHand_RayCastEnv, Stuff.Sword.noHand_direction, Stuff.Sword.noHand_speed, Stuff.Sword.noHand_swordDrop_acceleration, Stuff.Sword.noHand_swordDrop_downMax, Stuff.Sword.noHand_swordFly_deceleration.
Referenced by Stuff.Sword.Motion_NoHand.