IngameDebugConsole::DebugsOnScrollListener
ScrollRect IngameDebugConsole.DebugsOnScrollListener.debugsScrollRect
DebugLogManager IngameDebugConsole.DebugsOnScrollListener.debugLogManager
void IngameDebugConsole.DebugsOnScrollListener.OnScroll(PointerEventData data)
References IngameDebugConsole.DebugsOnScrollListener.IsScrollbarAtBottom.
void IngameDebugConsole.DebugsOnScrollListener.OnBeginDrag(PointerEventData data)
void IngameDebugConsole.DebugsOnScrollListener.OnEndDrag(PointerEventData data)
References IngameDebugConsole.DebugsOnScrollListener.IsScrollbarAtBottom.
void IngameDebugConsole.DebugsOnScrollListener.OnScrollbarDragStart(BaseEventData data)
void IngameDebugConsole.DebugsOnScrollListener.OnScrollbarDragEnd(BaseEventData data)
References IngameDebugConsole.DebugsOnScrollListener.IsScrollbarAtBottom.
bool IngameDebugConsole.DebugsOnScrollListener.IsScrollbarAtBottom()
Referenced by IngameDebugConsole.DebugsOnScrollListener.OnEndDrag, IngameDebugConsole.DebugsOnScrollListener.OnScroll, IngameDebugConsole.DebugsOnScrollListener.OnScrollbarDragEnd.