IngameDebugConsole::DebugLogManager
DebugLogManager IngameDebugConsole.DebugLogManager.Instance
Referenced by IngameDebugConsole.DebugLogManager.Awake, IngameDebugConsole.DebugLogConsole.LogAllCommands, IngameDebugConsole.DebugLogConsole.LogSystemInfo, IngameDebugConsole.DebugLogManager.OnDisable, IngameDebugConsole.DebugLogManager.OnEnable.
bool IngameDebugConsole.DebugLogManager.IsLogWindowVisible
bool IngameDebugConsole.DebugLogManager.PopupEnabled
Referenced by IngameDebugConsole.DebugLogManager.Start.
bool IngameDebugConsole.DebugLogManager.singleton
Referenced by IngameDebugConsole.DebugLogManager.Awake.
float IngameDebugConsole.DebugLogManager.minimumHeight
Referenced by IngameDebugConsole.DebugLogManager.Awake, IngameDebugConsole.DebugLogManager.Resize.
bool IngameDebugConsole.DebugLogManager.enablePopup
Referenced by IngameDebugConsole.DebugLogManager.Start.
bool IngameDebugConsole.DebugLogManager.startInPopupMode
Referenced by IngameDebugConsole.DebugLogManager.Start.
bool IngameDebugConsole.DebugLogManager.startMinimized
Referenced by IngameDebugConsole.DebugLogManager.Start.
bool IngameDebugConsole.DebugLogManager.toggleWithKey
Referenced by IngameDebugConsole.DebugLogManager.Update.
KeyCode IngameDebugConsole.DebugLogManager.toggleKey
Referenced by IngameDebugConsole.DebugLogManager.Update.
bool IngameDebugConsole.DebugLogManager.enableSearchbar
Referenced by IngameDebugConsole.DebugLogManager.Awake.
float IngameDebugConsole.DebugLogManager.topSearchbarMinWidth
Referenced by IngameDebugConsole.DebugLogManager.LateUpdate.
bool IngameDebugConsole.DebugLogManager.clearCommandAfterExecution
Referenced by IngameDebugConsole.DebugLogManager.OnValidateCommand.
int IngameDebugConsole.DebugLogManager.commandHistorySize
Referenced by IngameDebugConsole.DebugLogManager.Awake.
bool IngameDebugConsole.DebugLogManager.showCommandSuggestions
Referenced by IngameDebugConsole.DebugLogManager.LateUpdate, IngameDebugConsole.DebugLogManager.RefreshCommandSuggestions.
bool IngameDebugConsole.DebugLogManager.receiveLogcatLogsInAndroid
Referenced by IngameDebugConsole.DebugLogManager.OnEnable.
string IngameDebugConsole.DebugLogManager.logcatArguments
Referenced by IngameDebugConsole.DebugLogManager.OnEnable.
bool IngameDebugConsole.DebugLogManager.avoidScreenCutout
Referenced by IngameDebugConsole.DebugLogManager.CheckScreenCutout.
int IngameDebugConsole.DebugLogManager.maxLogLength
Referenced by IngameDebugConsole.DebugLogManager.ReceivedLog.
DebugLogItem IngameDebugConsole.DebugLogManager.logItemPrefab
Referenced by IngameDebugConsole.DebugLogManager.PopLogItem.
Text IngameDebugConsole.DebugLogManager.commandSuggestionPrefab
Referenced by IngameDebugConsole.DebugLogManager.RefreshCommandSuggestions.
Sprite IngameDebugConsole.DebugLogManager.infoLog
Referenced by IngameDebugConsole.DebugLogManager.Awake, IngameDebugConsole.DebugLogManager.FilterLogs, IngameDebugConsole.DebugLogManager.ProcessLog.
Sprite IngameDebugConsole.DebugLogManager.warningLog
Referenced by IngameDebugConsole.DebugLogManager.Awake, IngameDebugConsole.DebugLogManager.FilterLogs, IngameDebugConsole.DebugLogManager.ProcessLog.
Sprite IngameDebugConsole.DebugLogManager.errorLog
Referenced by IngameDebugConsole.DebugLogManager.Awake, IngameDebugConsole.DebugLogManager.ProcessLog.
Dictionary<LogType, Sprite> IngameDebugConsole.DebugLogManager.logSpriteRepresentations
Referenced by IngameDebugConsole.DebugLogManager.Awake, IngameDebugConsole.DebugLogManager.ProcessLog.
Color IngameDebugConsole.DebugLogManager.collapseButtonNormalColor
Referenced by IngameDebugConsole.DebugLogManager.CollapseButtonPressed.
Color IngameDebugConsole.DebugLogManager.collapseButtonSelectedColor
Referenced by IngameDebugConsole.DebugLogManager.CollapseButtonPressed.
Color IngameDebugConsole.DebugLogManager.filterButtonsNormalColor
Referenced by IngameDebugConsole.DebugLogManager.FilterErrorButtonPressed, IngameDebugConsole.DebugLogManager.FilterLogButtonPressed, IngameDebugConsole.DebugLogManager.FilterWarningButtonPressed.
Color IngameDebugConsole.DebugLogManager.filterButtonsSelectedColor
Referenced by IngameDebugConsole.DebugLogManager.Awake, IngameDebugConsole.DebugLogManager.FilterErrorButtonPressed, IngameDebugConsole.DebugLogManager.FilterLogButtonPressed, IngameDebugConsole.DebugLogManager.FilterWarningButtonPressed.
string IngameDebugConsole.DebugLogManager.commandSuggestionHighlightStart
Referenced by IngameDebugConsole.DebugLogManager.RefreshCommandSuggestions.
string IngameDebugConsole.DebugLogManager.commandSuggestionHighlightEnd
Referenced by IngameDebugConsole.DebugLogManager.RefreshCommandSuggestions.
RectTransform IngameDebugConsole.DebugLogManager.logWindowTR
Referenced by IngameDebugConsole.DebugLogManager.CheckScreenCutout.
RectTransform IngameDebugConsole.DebugLogManager.canvasTR
Referenced by IngameDebugConsole.DebugLogManager.Awake, IngameDebugConsole.DebugLogManager.CheckScreenCutout, IngameDebugConsole.DebugLogManager.Resize.
RectTransform IngameDebugConsole.DebugLogManager.logItemsContainer
Referenced by IngameDebugConsole.DebugLogManager.PopLogItem.
RectTransform IngameDebugConsole.DebugLogManager.commandSuggestionsContainer
Referenced by IngameDebugConsole.DebugLogManager.Awake, IngameDebugConsole.DebugLogManager.OnEndEditCommand, IngameDebugConsole.DebugLogManager.RefreshCommandSuggestions.
InputField IngameDebugConsole.DebugLogManager.commandInputField
Referenced by IngameDebugConsole.DebugLogManager.HideLogWindow, IngameDebugConsole.DebugLogManager.LateUpdate, IngameDebugConsole.DebugLogManager.OnValidateCommand.
Button IngameDebugConsole.DebugLogManager.hideButton
Button IngameDebugConsole.DebugLogManager.clearButton
Image IngameDebugConsole.DebugLogManager.collapseButton
Image IngameDebugConsole.DebugLogManager.filterInfoButton
Image IngameDebugConsole.DebugLogManager.filterWarningButton
Image IngameDebugConsole.DebugLogManager.filterErrorButton
Text IngameDebugConsole.DebugLogManager.infoEntryCountText
Text IngameDebugConsole.DebugLogManager.warningEntryCountText
Text IngameDebugConsole.DebugLogManager.errorEntryCountText
RectTransform IngameDebugConsole.DebugLogManager.searchbar
Referenced by IngameDebugConsole.DebugLogManager.Awake, IngameDebugConsole.DebugLogManager.LateUpdate.
RectTransform IngameDebugConsole.DebugLogManager.searchbarSlotTop
Referenced by IngameDebugConsole.DebugLogManager.LateUpdate.
RectTransform IngameDebugConsole.DebugLogManager.searchbarSlotBottom
Referenced by IngameDebugConsole.DebugLogManager.LateUpdate.
GameObject IngameDebugConsole.DebugLogManager.snapToBottomButton
Referenced by IngameDebugConsole.DebugLogManager.LateUpdate.
CanvasGroup IngameDebugConsole.DebugLogManager.logWindowCanvasGroup
DebugLogPopup IngameDebugConsole.DebugLogManager.popupManager
ScrollRect IngameDebugConsole.DebugLogManager.logItemsScrollRect
Referenced by IngameDebugConsole.DebugLogManager.Awake.
RectTransform IngameDebugConsole.DebugLogManager.logItemsScrollRectTR
Referenced by IngameDebugConsole.DebugLogManager.Awake.
Vector2 IngameDebugConsole.DebugLogManager.logItemsScrollRectOriginalSize
Referenced by IngameDebugConsole.DebugLogManager.Awake, IngameDebugConsole.DebugLogManager.LateUpdate.
DebugLogRecycledListView IngameDebugConsole.DebugLogManager.recycledListView
Referenced by IngameDebugConsole.DebugLogManager.PopLogItem.
bool IngameDebugConsole.DebugLogManager.isLogWindowVisible
Referenced by IngameDebugConsole.DebugLogManager.HideLogWindow, IngameDebugConsole.DebugLogManager.LateUpdate, IngameDebugConsole.DebugLogManager.ProcessLog, IngameDebugConsole.DebugLogManager.ShowLogWindow, IngameDebugConsole.DebugLogManager.Update.
bool IngameDebugConsole.DebugLogManager.screenDimensionsChanged
Referenced by IngameDebugConsole.DebugLogManager.LateUpdate, IngameDebugConsole.DebugLogManager.OnRectTransformDimensionsChange.
int IngameDebugConsole.DebugLogManager.infoEntryCount
Referenced by IngameDebugConsole.DebugLogManager.ClearLogs, IngameDebugConsole.DebugLogManager.ProcessLog.
int IngameDebugConsole.DebugLogManager.warningEntryCount
Referenced by IngameDebugConsole.DebugLogManager.ClearLogs, IngameDebugConsole.DebugLogManager.ProcessLog.
int IngameDebugConsole.DebugLogManager.errorEntryCount
Referenced by IngameDebugConsole.DebugLogManager.ClearLogs, IngameDebugConsole.DebugLogManager.ProcessLog.
bool IngameDebugConsole.DebugLogManager.isCollapseOn
Referenced by IngameDebugConsole.DebugLogManager.CollapseButtonPressed, IngameDebugConsole.DebugLogManager.FilterLogs, IngameDebugConsole.DebugLogManager.ProcessLog.
DebugLogFilter IngameDebugConsole.DebugLogManager.logFilter
Referenced by IngameDebugConsole.DebugLogManager.FilterErrorButtonPressed, IngameDebugConsole.DebugLogManager.FilterLogButtonPressed, IngameDebugConsole.DebugLogManager.FilterLogs, IngameDebugConsole.DebugLogManager.FilterWarningButtonPressed, IngameDebugConsole.DebugLogManager.ProcessLog.
string IngameDebugConsole.DebugLogManager.searchTerm
Referenced by IngameDebugConsole.DebugLogManager.FilterLogs, IngameDebugConsole.DebugLogManager.ProcessLog, IngameDebugConsole.DebugLogManager.SearchTermChanged.
bool IngameDebugConsole.DebugLogManager.isInSearchMode
Referenced by IngameDebugConsole.DebugLogManager.FilterLogs, IngameDebugConsole.DebugLogManager.ProcessLog, IngameDebugConsole.DebugLogManager.SearchTermChanged.
bool IngameDebugConsole.DebugLogManager.snapToBottom
Referenced by IngameDebugConsole.DebugLogManager.ClearLogs, IngameDebugConsole.DebugLogManager.CollapseButtonPressed, IngameDebugConsole.DebugLogManager.LateUpdate, IngameDebugConsole.DebugLogManager.SetSnapToBottom.
List<DebugLogEntry> IngameDebugConsole.DebugLogManager.collapsedLogEntries
Referenced by IngameDebugConsole.DebugLogManager.Awake, IngameDebugConsole.DebugLogManager.FilterLogs, IngameDebugConsole.DebugLogManager.GetAllLogs, IngameDebugConsole.DebugLogManager.ProcessLog.
Dictionary<DebugLogEntry, int> IngameDebugConsole.DebugLogManager.collapsedLogEntriesMap
Referenced by IngameDebugConsole.DebugLogManager.Awake, IngameDebugConsole.DebugLogManager.ProcessLog.
DebugLogIndexList IngameDebugConsole.DebugLogManager.uncollapsedLogEntriesIndices
Referenced by IngameDebugConsole.DebugLogManager.Awake, IngameDebugConsole.DebugLogManager.FilterLogs, IngameDebugConsole.DebugLogManager.GetAllLogs.
DebugLogIndexList IngameDebugConsole.DebugLogManager.indicesOfListEntriesToShow
Referenced by IngameDebugConsole.DebugLogManager.Awake, IngameDebugConsole.DebugLogManager.FilterLogs.
DynamicCircularBuffer<QueuedDebugLogEntry> IngameDebugConsole.DebugLogManager.queuedLogEntries
Referenced by IngameDebugConsole.DebugLogManager.Awake.
object IngameDebugConsole.DebugLogManager.logEntriesLock
Referenced by IngameDebugConsole.DebugLogManager.Awake, IngameDebugConsole.DebugLogManager.LateUpdate, IngameDebugConsole.DebugLogManager.ReceivedLog.
int IngameDebugConsole.DebugLogManager.pendingLogToAutoExpand
Referenced by IngameDebugConsole.DebugLogManager.ExpandLatestPendingLog, IngameDebugConsole.DebugLogManager.ProcessLog.
List<Text> IngameDebugConsole.DebugLogManager.commandSuggestionInstances
Referenced by IngameDebugConsole.DebugLogManager.Awake, IngameDebugConsole.DebugLogManager.RefreshCommandSuggestions.
int IngameDebugConsole.DebugLogManager.visibleCommandSuggestionInstances
Referenced by IngameDebugConsole.DebugLogManager.RefreshCommandSuggestions.
List<ConsoleMethodInfo> IngameDebugConsole.DebugLogManager.matchingCommandSuggestions
Referenced by IngameDebugConsole.DebugLogManager.Awake, IngameDebugConsole.DebugLogManager.RefreshCommandSuggestions.
List<int> IngameDebugConsole.DebugLogManager.commandCaretIndexIncrements
Referenced by IngameDebugConsole.DebugLogManager.Awake, IngameDebugConsole.DebugLogManager.RefreshCommandSuggestions.
StringBuilder IngameDebugConsole.DebugLogManager.commandSuggestionsStringBuilder
Referenced by IngameDebugConsole.DebugLogManager.Awake.
string IngameDebugConsole.DebugLogManager.commandInputFieldPrevCommand
Referenced by IngameDebugConsole.DebugLogManager.RefreshCommandSuggestions.
string IngameDebugConsole.DebugLogManager.commandInputFieldPrevCommandName
Referenced by IngameDebugConsole.DebugLogManager.RefreshCommandSuggestions.
int IngameDebugConsole.DebugLogManager.commandInputFieldPrevParamCount
Referenced by IngameDebugConsole.DebugLogManager.RefreshCommandSuggestions.
int IngameDebugConsole.DebugLogManager.commandInputFieldPrevCaretPos
Referenced by IngameDebugConsole.DebugLogManager.LateUpdate, IngameDebugConsole.DebugLogManager.RefreshCommandSuggestions.
int IngameDebugConsole.DebugLogManager.commandInputFieldPrevCaretArgumentIndex
Referenced by IngameDebugConsole.DebugLogManager.RefreshCommandSuggestions.
List<DebugLogEntry> IngameDebugConsole.DebugLogManager.pooledLogEntries
Referenced by IngameDebugConsole.DebugLogManager.Awake, IngameDebugConsole.DebugLogManager.ProcessLog.
List<DebugLogItem> IngameDebugConsole.DebugLogManager.pooledLogItems
Referenced by IngameDebugConsole.DebugLogManager.Awake, IngameDebugConsole.DebugLogManager.PopLogItem.
CircularBuffer<string> IngameDebugConsole.DebugLogManager.commandHistory
Referenced by IngameDebugConsole.DebugLogManager.Awake, IngameDebugConsole.DebugLogManager.LateUpdate, IngameDebugConsole.DebugLogManager.OnValidateCommand.
int IngameDebugConsole.DebugLogManager.commandHistoryIndex
Referenced by IngameDebugConsole.DebugLogManager.LateUpdate, IngameDebugConsole.DebugLogManager.OnValidateCommand.
string IngameDebugConsole.DebugLogManager.unfinishedCommand
Referenced by IngameDebugConsole.DebugLogManager.LateUpdate, IngameDebugConsole.DebugLogManager.OnValidateCommand.
PointerEventData IngameDebugConsole.DebugLogManager.nullPointerEventData
Referenced by IngameDebugConsole.DebugLogManager.Awake, IngameDebugConsole.DebugLogManager.ValidateScrollPosition.
System.Action IngameDebugConsole.DebugLogManager.OnLogWindowHidden
Referenced by IngameDebugConsole.DebugLogManager.HideLogWindow.
System.Action IngameDebugConsole.DebugLogManager.OnLogWindowShown
Referenced by IngameDebugConsole.DebugLogManager.ShowLogWindow.
void IngameDebugConsole.DebugLogManager.Awake()
References IngameDebugConsole.DebugLogManager.canvasTR, IngameDebugConsole.DebugLogManager.ClearLogs, IngameDebugConsole.DebugLogManager.CollapseButtonPressed, IngameDebugConsole.DebugLogManager.collapsedLogEntries, IngameDebugConsole.DebugLogManager.collapsedLogEntriesMap, IngameDebugConsole.DebugLogManager.commandCaretIndexIncrements, IngameDebugConsole.DebugLogManager.commandHistory, IngameDebugConsole.DebugLogManager.commandHistorySize, IngameDebugConsole.DebugLogManager.commandSuggestionInstances, IngameDebugConsole.DebugLogManager.commandSuggestionsContainer, IngameDebugConsole.DebugLogManager.commandSuggestionsStringBuilder, IngameDebugConsole.DebugLogManager.enableSearchbar, IngameDebugConsole.DebugLogManager.errorLog, IngameDebugConsole.DebugLogManager.filterButtonsSelectedColor, IngameDebugConsole.DebugLogManager.FilterErrorButtonPressed, IngameDebugConsole.DebugLogManager.FilterLogButtonPressed, IngameDebugConsole.DebugLogManager.FilterWarningButtonPressed, IngameDebugConsole.DebugLogManager.HideLogWindow, IngameDebugConsole.DebugLogManager.indicesOfListEntriesToShow, IngameDebugConsole.DebugLogManager.infoLog, IngameDebugConsole.DebugLogManager.Instance, IngameDebugConsole.DebugLogManager.logEntriesLock, IngameDebugConsole.DebugLogManager.logItemsScrollRect, IngameDebugConsole.DebugLogManager.logItemsScrollRectOriginalSize, IngameDebugConsole.DebugLogManager.logItemsScrollRectTR, IngameDebugConsole.DebugLogManager.logSpriteRepresentations, IngameDebugConsole.DebugLogManager.matchingCommandSuggestions, IngameDebugConsole.DebugLogManager.minimumHeight, IngameDebugConsole.DebugLogManager.nullPointerEventData, IngameDebugConsole.DebugLogManager.OnEndEditCommand, IngameDebugConsole.DebugLogManager.OnValidateCommand, IngameDebugConsole.DebugLogManager.pooledLogEntries, IngameDebugConsole.DebugLogManager.pooledLogItems, IngameDebugConsole.DebugLogManager.queuedLogEntries, IngameDebugConsole.DebugLogManager.RefreshCommandSuggestions, IngameDebugConsole.DebugLogManager.searchbar, IngameDebugConsole.DebugLogManager.SearchTermChanged, IngameDebugConsole.DebugLogManager.SetSnapToBottom, IngameDebugConsole.DebugLogManager.singleton, IngameDebugConsole.DebugLogManager.uncollapsedLogEntriesIndices, IngameDebugConsole.DebugLogManager.warningLog.
void IngameDebugConsole.DebugLogManager.OnEnable()
References IngameDebugConsole.DebugLogManager.Instance, IngameDebugConsole.DebugLogManager.logcatArguments, IngameDebugConsole.DebugLogManager.ReceivedLog, IngameDebugConsole.DebugLogManager.receiveLogcatLogsInAndroid, IngameDebugConsole.DebugLogManager.SaveLogsToFile.
void IngameDebugConsole.DebugLogManager.OnDisable()
References IngameDebugConsole.DebugLogManager.Instance, IngameDebugConsole.DebugLogManager.ReceivedLog.
void IngameDebugConsole.DebugLogManager.Start()
References IngameDebugConsole.DebugLogManager.enablePopup, IngameDebugConsole.DebugLogManager.HideLogWindow, IngameDebugConsole.DebugLogManager.PopupEnabled, IngameDebugConsole.DebugLogManager.ShowLogWindow, IngameDebugConsole.DebugLogManager.startInPopupMode, IngameDebugConsole.DebugLogManager.startMinimized.
void IngameDebugConsole.DebugLogManager.OnRectTransformDimensionsChange()
References IngameDebugConsole.DebugLogManager.screenDimensionsChanged.
void IngameDebugConsole.DebugLogManager.Update()
References IngameDebugConsole.DebugLogManager.HideLogWindow, IngameDebugConsole.DebugLogManager.isLogWindowVisible, IngameDebugConsole.DebugLogManager.ShowLogWindow, IngameDebugConsole.DebugLogManager.toggleKey, IngameDebugConsole.DebugLogManager.toggleWithKey.
void IngameDebugConsole.DebugLogManager.LateUpdate()
References IngameDebugConsole.DebugLogManager.CheckScreenCutout, IngameDebugConsole.DebugLogManager.commandHistory, IngameDebugConsole.DebugLogManager.commandHistoryIndex, IngameDebugConsole.DebugLogManager.commandInputField, IngameDebugConsole.DebugLogManager.commandInputFieldPrevCaretPos, IngameDebugConsole.DebugLogManager.isLogWindowVisible, IngameDebugConsole.DebugLogManager.logEntriesLock, IngameDebugConsole.DebugLogManager.logItemsScrollRectOriginalSize, IngameDebugConsole.DebugLogManager.ProcessLog, IngameDebugConsole.DebugLogManager.ReceivedLog, IngameDebugConsole.DebugLogManager.RefreshCommandSuggestions, IngameDebugConsole.DebugLogManager.screenDimensionsChanged, IngameDebugConsole.DebugLogManager.searchbar, IngameDebugConsole.DebugLogManager.searchbarSlotBottom, IngameDebugConsole.DebugLogManager.searchbarSlotTop, IngameDebugConsole.DebugLogManager.showCommandSuggestions, IngameDebugConsole.DebugLogManager.snapToBottom, IngameDebugConsole.DebugLogManager.snapToBottomButton, IngameDebugConsole.DebugLogManager.topSearchbarMinWidth, IngameDebugConsole.DebugLogManager.unfinishedCommand.
char IngameDebugConsole.DebugLogManager.OnValidateCommand(string text, int charIndex, char addedChar)
References IngameDebugConsole.DebugLogManager.clearCommandAfterExecution, IngameDebugConsole.DebugLogManager.commandHistory, IngameDebugConsole.DebugLogManager.commandHistoryIndex, IngameDebugConsole.DebugLogManager.commandInputField, IngameDebugConsole.DebugLogManager.SetSnapToBottom, IngameDebugConsole.DebugLogManager.unfinishedCommand.
Referenced by IngameDebugConsole.DebugLogManager.Awake.
void IngameDebugConsole.DebugLogManager.ReceivedLog(string logString, string stackTrace, LogType logType)
References IngameDebugConsole.DebugLogManager.logEntriesLock, IngameDebugConsole.DebugLogManager.maxLogLength.
Referenced by IngameDebugConsole.DebugLogManager.LateUpdate, IngameDebugConsole.DebugLogManager.OnDisable, IngameDebugConsole.DebugLogManager.OnEnable.
void IngameDebugConsole.DebugLogManager.ProcessLog(QueuedDebugLogEntry queuedLogEntry)
References IngameDebugConsole.DebugLogManager.collapsedLogEntries, IngameDebugConsole.DebugLogManager.collapsedLogEntriesMap, IngameDebugConsole.DebugLogManager.errorEntryCount, IngameDebugConsole.DebugLogManager.errorLog, IngameDebugConsole.DebugLogManager.infoEntryCount, IngameDebugConsole.DebugLogManager.infoLog, IngameDebugConsole.DebugLogManager.isCollapseOn, IngameDebugConsole.DebugLogManager.isInSearchMode, IngameDebugConsole.DebugLogManager.isLogWindowVisible, IngameDebugConsole.DebugLogManager.logFilter, IngameDebugConsole.DebugLogManager.logSpriteRepresentations, IngameDebugConsole.QueuedDebugLogEntry.MatchesSearchTerm, IngameDebugConsole.DebugLogManager.pendingLogToAutoExpand, IngameDebugConsole.DebugLogManager.pooledLogEntries, IngameDebugConsole.DebugLogManager.searchTerm, IngameDebugConsole.DebugLogManager.warningEntryCount, IngameDebugConsole.DebugLogManager.warningLog.
Referenced by IngameDebugConsole.DebugLogManager.LateUpdate.
void IngameDebugConsole.DebugLogManager.CollapseButtonPressed()
References IngameDebugConsole.DebugLogManager.collapseButtonNormalColor, IngameDebugConsole.DebugLogManager.collapseButtonSelectedColor, IngameDebugConsole.DebugLogManager.FilterLogs, IngameDebugConsole.DebugLogManager.isCollapseOn, IngameDebugConsole.DebugLogManager.snapToBottom.
Referenced by IngameDebugConsole.DebugLogManager.Awake.
void IngameDebugConsole.DebugLogManager.FilterLogButtonPressed()
References IngameDebugConsole.DebugLogManager.filterButtonsNormalColor, IngameDebugConsole.DebugLogManager.filterButtonsSelectedColor, IngameDebugConsole.DebugLogManager.FilterLogs, IngameDebugConsole.DebugLogManager.logFilter.
Referenced by IngameDebugConsole.DebugLogManager.Awake.
void IngameDebugConsole.DebugLogManager.FilterWarningButtonPressed()
References IngameDebugConsole.DebugLogManager.filterButtonsNormalColor, IngameDebugConsole.DebugLogManager.filterButtonsSelectedColor, IngameDebugConsole.DebugLogManager.FilterLogs, IngameDebugConsole.DebugLogManager.logFilter.
Referenced by IngameDebugConsole.DebugLogManager.Awake.
void IngameDebugConsole.DebugLogManager.FilterErrorButtonPressed()
References IngameDebugConsole.DebugLogManager.filterButtonsNormalColor, IngameDebugConsole.DebugLogManager.filterButtonsSelectedColor, IngameDebugConsole.DebugLogManager.FilterLogs, IngameDebugConsole.DebugLogManager.logFilter.
Referenced by IngameDebugConsole.DebugLogManager.Awake.
void IngameDebugConsole.DebugLogManager.SearchTermChanged(string searchTerm)
References IngameDebugConsole.DebugLogManager.FilterLogs, IngameDebugConsole.DebugLogManager.isInSearchMode, IngameDebugConsole.DebugLogManager.searchTerm.
Referenced by IngameDebugConsole.DebugLogManager.Awake.
void IngameDebugConsole.DebugLogManager.RefreshCommandSuggestions(string command)
References IngameDebugConsole.DebugLogManager.commandCaretIndexIncrements, IngameDebugConsole.DebugLogManager.commandInputFieldPrevCaretArgumentIndex, IngameDebugConsole.DebugLogManager.commandInputFieldPrevCaretPos, IngameDebugConsole.DebugLogManager.commandInputFieldPrevCommand, IngameDebugConsole.DebugLogManager.commandInputFieldPrevCommandName, IngameDebugConsole.DebugLogManager.commandInputFieldPrevParamCount, IngameDebugConsole.DebugLogManager.commandSuggestionHighlightEnd, IngameDebugConsole.DebugLogManager.commandSuggestionHighlightStart, IngameDebugConsole.DebugLogManager.commandSuggestionInstances, IngameDebugConsole.DebugLogManager.commandSuggestionPrefab, IngameDebugConsole.DebugLogManager.commandSuggestionsContainer, IngameDebugConsole.DebugLogManager.matchingCommandSuggestions, IngameDebugConsole.DebugLogManager.OnEndEditCommand, IngameDebugConsole.ConsoleMethodInfo.parameters, IngameDebugConsole.DebugLogManager.showCommandSuggestions, IngameDebugConsole.DebugLogManager.visibleCommandSuggestionInstances.
Referenced by IngameDebugConsole.DebugLogManager.Awake, IngameDebugConsole.DebugLogManager.LateUpdate.
void IngameDebugConsole.DebugLogManager.OnEndEditCommand(string command)
References IngameDebugConsole.DebugLogManager.commandSuggestionsContainer.
Referenced by IngameDebugConsole.DebugLogManager.Awake, IngameDebugConsole.DebugLogManager.RefreshCommandSuggestions.
void IngameDebugConsole.DebugLogManager.FilterLogs()
References IngameDebugConsole.DebugLogIndexList.Add, IngameDebugConsole.DebugLogManager.collapsedLogEntries, IngameDebugConsole.DebugLogIndexList.Count, IngameDebugConsole.DebugLogManager.indicesOfListEntriesToShow, IngameDebugConsole.DebugLogManager.infoLog, IngameDebugConsole.DebugLogManager.isCollapseOn, IngameDebugConsole.DebugLogManager.isInSearchMode, IngameDebugConsole.DebugLogManager.logFilter, IngameDebugConsole.DebugLogEntry.logTypeSpriteRepresentation, IngameDebugConsole.DebugLogEntry.MatchesSearchTerm, IngameDebugConsole.DebugLogManager.searchTerm, IngameDebugConsole.DebugLogManager.uncollapsedLogEntriesIndices, IngameDebugConsole.DebugLogManager.ValidateScrollPosition, IngameDebugConsole.DebugLogManager.warningLog.
Referenced by IngameDebugConsole.DebugLogManager.CollapseButtonPressed, IngameDebugConsole.DebugLogManager.FilterErrorButtonPressed, IngameDebugConsole.DebugLogManager.FilterLogButtonPressed, IngameDebugConsole.DebugLogManager.FilterWarningButtonPressed, IngameDebugConsole.DebugLogManager.SearchTermChanged.
void IngameDebugConsole.DebugLogManager.SaveLogsToFile()
References IngameDebugConsole.DebugLogManager.GetAllLogs.
Referenced by IngameDebugConsole.DebugLogManager.OnEnable.
void IngameDebugConsole.DebugLogManager.CheckScreenCutout()
References IngameDebugConsole.DebugLogManager.avoidScreenCutout, IngameDebugConsole.DebugLogManager.canvasTR, IngameDebugConsole.DebugLogManager.logWindowTR.
Referenced by IngameDebugConsole.DebugLogManager.LateUpdate.
void IngameDebugConsole.DebugLogManager.ShowLogWindow()
References IngameDebugConsole.DebugLogManager.isLogWindowVisible, IngameDebugConsole.DebugLogManager.OnLogWindowShown.
Referenced by IngameDebugConsole.DebugLogManager.Start, IngameDebugConsole.DebugLogManager.Update.
void IngameDebugConsole.DebugLogManager.HideLogWindow()
References IngameDebugConsole.DebugLogManager.commandInputField, IngameDebugConsole.DebugLogManager.isLogWindowVisible, IngameDebugConsole.DebugLogManager.OnLogWindowHidden.
Referenced by IngameDebugConsole.DebugLogManager.Awake, IngameDebugConsole.DebugLogManager.Start, IngameDebugConsole.DebugLogManager.Update.
void IngameDebugConsole.DebugLogManager.SetSnapToBottom(bool snapToBottom)
References IngameDebugConsole.DebugLogManager.snapToBottom.
Referenced by IngameDebugConsole.DebugLogManager.Awake, IngameDebugConsole.DebugLogManager.OnValidateCommand.
void IngameDebugConsole.DebugLogManager.ClearLogs()
References IngameDebugConsole.DebugLogManager.errorEntryCount, IngameDebugConsole.DebugLogManager.infoEntryCount, IngameDebugConsole.DebugLogManager.snapToBottom, IngameDebugConsole.DebugLogManager.warningEntryCount.
Referenced by IngameDebugConsole.DebugLogManager.Awake.
string IngameDebugConsole.DebugLogManager.GetAllLogs()
References IngameDebugConsole.DebugLogManager.collapsedLogEntries, IngameDebugConsole.DebugLogEntry.stackTrace, IngameDebugConsole.DebugLogManager.uncollapsedLogEntriesIndices.
Referenced by IngameDebugConsole.DebugLogManager.SaveLogsToFile.
void IngameDebugConsole.DebugLogManager.ValidateScrollPosition()
References IngameDebugConsole.DebugLogManager.nullPointerEventData.
Referenced by IngameDebugConsole.DebugLogManager.FilterLogs.
void IngameDebugConsole.DebugLogManager.ExpandLatestPendingLog()
References IngameDebugConsole.DebugLogManager.pendingLogToAutoExpand.
void IngameDebugConsole.DebugLogManager.Resize(PointerEventData eventData)
References IngameDebugConsole.DebugLogManager.canvasTR, IngameDebugConsole.DebugLogManager.minimumHeight.
void IngameDebugConsole.DebugLogManager.PoolLogItem(DebugLogItem logItem)
Referenced by IngameDebugConsole.DebugLogRecycledListView.DestroyLogItemsBetweenIndices.
DebugLogItem IngameDebugConsole.DebugLogManager.PopLogItem()
References IngameDebugConsole.DebugLogManager.logItemPrefab, IngameDebugConsole.DebugLogManager.logItemsContainer, IngameDebugConsole.DebugLogManager.pooledLogItems, IngameDebugConsole.DebugLogManager.recycledListView.