IngameDebugConsole::DebugLogPopup
RectTransform IngameDebugConsole.DebugLogPopup.popupTransform
Referenced by IngameDebugConsole.DebugLogPopup.Awake.
Vector2 IngameDebugConsole.DebugLogPopup.halfSize
Referenced by IngameDebugConsole.DebugLogPopup.OnEndDrag, IngameDebugConsole.DebugLogPopup.OnViewportDimensionsChanged, IngameDebugConsole.DebugLogPopup.Start.
Image IngameDebugConsole.DebugLogPopup.backgroundImage
Referenced by IngameDebugConsole.DebugLogPopup.Awake.
CanvasGroup IngameDebugConsole.DebugLogPopup.canvasGroup
Referenced by IngameDebugConsole.DebugLogPopup.Awake.
DebugLogManager IngameDebugConsole.DebugLogPopup.debugManager
Text IngameDebugConsole.DebugLogPopup.newInfoCountText
Text IngameDebugConsole.DebugLogPopup.newWarningCountText
Text IngameDebugConsole.DebugLogPopup.newErrorCountText
Color IngameDebugConsole.DebugLogPopup.alertColorInfo
Referenced by IngameDebugConsole.DebugLogPopup.NewInfoLogArrived.
Color IngameDebugConsole.DebugLogPopup.alertColorWarning
Referenced by IngameDebugConsole.DebugLogPopup.NewWarningLogArrived.
Color IngameDebugConsole.DebugLogPopup.alertColorError
Referenced by IngameDebugConsole.DebugLogPopup.NewErrorLogArrived.
int IngameDebugConsole.DebugLogPopup.newInfoCount
Referenced by IngameDebugConsole.DebugLogPopup.NewInfoLogArrived, IngameDebugConsole.DebugLogPopup.Reset.
int IngameDebugConsole.DebugLogPopup.newWarningCount
Referenced by IngameDebugConsole.DebugLogPopup.NewInfoLogArrived, IngameDebugConsole.DebugLogPopup.NewWarningLogArrived, IngameDebugConsole.DebugLogPopup.Reset.
int IngameDebugConsole.DebugLogPopup.newErrorCount
Referenced by IngameDebugConsole.DebugLogPopup.NewErrorLogArrived, IngameDebugConsole.DebugLogPopup.NewInfoLogArrived, IngameDebugConsole.DebugLogPopup.NewWarningLogArrived, IngameDebugConsole.DebugLogPopup.Reset.
Color IngameDebugConsole.DebugLogPopup.normalColor
Referenced by IngameDebugConsole.DebugLogPopup.Awake, IngameDebugConsole.DebugLogPopup.Reset.
bool IngameDebugConsole.DebugLogPopup.isPopupBeingDragged
Referenced by IngameDebugConsole.DebugLogPopup.Hide, IngameDebugConsole.DebugLogPopup.OnBeginDrag, IngameDebugConsole.DebugLogPopup.OnEndDrag, IngameDebugConsole.DebugLogPopup.OnPointerClick.
IEnumerator IngameDebugConsole.DebugLogPopup.moveToPosCoroutine
Referenced by IngameDebugConsole.DebugLogPopup.OnBeginDrag, IngameDebugConsole.DebugLogPopup.OnEndDrag.
void IngameDebugConsole.DebugLogPopup.Awake()
References IngameDebugConsole.DebugLogPopup.backgroundImage, IngameDebugConsole.DebugLogPopup.canvasGroup, IngameDebugConsole.DebugLogPopup.normalColor, IngameDebugConsole.DebugLogPopup.popupTransform.
void IngameDebugConsole.DebugLogPopup.Start()
References IngameDebugConsole.DebugLogPopup.halfSize.
void IngameDebugConsole.DebugLogPopup.Reset()
References IngameDebugConsole.DebugLogPopup.newErrorCount, IngameDebugConsole.DebugLogPopup.newInfoCount, IngameDebugConsole.DebugLogPopup.newWarningCount, IngameDebugConsole.DebugLogPopup.normalColor.
Referenced by IngameDebugConsole.DebugLogPopup.Show.
IEnumerator IngameDebugConsole.DebugLogPopup.MoveToPosAnimation(Vector3 targetPos)
Referenced by IngameDebugConsole.DebugLogPopup.OnEndDrag.
void IngameDebugConsole.DebugLogPopup.OnViewportDimensionsChanged()
References IngameDebugConsole.DebugLogPopup.halfSize, IngameDebugConsole.DebugLogPopup.OnEndDrag.
Referenced by IngameDebugConsole.DebugLogPopup.Show.
void IngameDebugConsole.DebugLogPopup.NewInfoLogArrived()
References IngameDebugConsole.DebugLogPopup.alertColorInfo, IngameDebugConsole.DebugLogPopup.newErrorCount, IngameDebugConsole.DebugLogPopup.newInfoCount, IngameDebugConsole.DebugLogPopup.newWarningCount.
void IngameDebugConsole.DebugLogPopup.NewWarningLogArrived()
References IngameDebugConsole.DebugLogPopup.alertColorWarning, IngameDebugConsole.DebugLogPopup.newErrorCount, IngameDebugConsole.DebugLogPopup.newWarningCount.
void IngameDebugConsole.DebugLogPopup.NewErrorLogArrived()
References IngameDebugConsole.DebugLogPopup.alertColorError, IngameDebugConsole.DebugLogPopup.newErrorCount.
void IngameDebugConsole.DebugLogPopup.OnPointerClick(PointerEventData data)
References IngameDebugConsole.DebugLogPopup.isPopupBeingDragged.
void IngameDebugConsole.DebugLogPopup.Show()
References IngameDebugConsole.DebugLogPopup.OnViewportDimensionsChanged, IngameDebugConsole.DebugLogPopup.Reset.
void IngameDebugConsole.DebugLogPopup.Hide()
References IngameDebugConsole.DebugLogPopup.isPopupBeingDragged.
void IngameDebugConsole.DebugLogPopup.OnBeginDrag(PointerEventData data)
References IngameDebugConsole.DebugLogPopup.isPopupBeingDragged, IngameDebugConsole.DebugLogPopup.moveToPosCoroutine.
void IngameDebugConsole.DebugLogPopup.OnDrag(PointerEventData data)
void IngameDebugConsole.DebugLogPopup.OnEndDrag(PointerEventData data)
References IngameDebugConsole.DebugLogPopup.halfSize, IngameDebugConsole.DebugLogPopup.isPopupBeingDragged, IngameDebugConsole.DebugLogPopup.MoveToPosAnimation, IngameDebugConsole.DebugLogPopup.moveToPosCoroutine.
Referenced by IngameDebugConsole.DebugLogPopup.OnViewportDimensionsChanged.