IngameDebugConsole::DebugLogRecycledListView
RectTransform IngameDebugConsole.DebugLogRecycledListView.transformComponent
RectTransform IngameDebugConsole.DebugLogRecycledListView.viewportTransform
DebugLogManager IngameDebugConsole.DebugLogRecycledListView.debugManager
Referenced by IngameDebugConsole.DebugLogRecycledListView.DestroyLogItemsBetweenIndices.
Color IngameDebugConsole.DebugLogRecycledListView.logItemNormalColor1
Referenced by IngameDebugConsole.DebugLogRecycledListView.ColorLogItem.
Color IngameDebugConsole.DebugLogRecycledListView.logItemNormalColor2
Referenced by IngameDebugConsole.DebugLogRecycledListView.ColorLogItem.
Color IngameDebugConsole.DebugLogRecycledListView.logItemSelectedColor
Referenced by IngameDebugConsole.DebugLogRecycledListView.ColorLogItem.
DebugLogManager IngameDebugConsole.DebugLogRecycledListView.manager
Referenced by IngameDebugConsole.DebugLogRecycledListView.Initialize.
ScrollRect IngameDebugConsole.DebugLogRecycledListView.scrollView
Referenced by IngameDebugConsole.DebugLogRecycledListView.Awake.
float IngameDebugConsole.DebugLogRecycledListView.logItemHeight
Referenced by IngameDebugConsole.DebugLogRecycledListView.CalculateContentHeight, IngameDebugConsole.DebugLogRecycledListView.CreateLogItemAtIndex, IngameDebugConsole.DebugLogRecycledListView.Initialize, IngameDebugConsole.DebugLogRecycledListView.OnLogItemClickedInternal, IngameDebugConsole.DebugLogRecycledListView.SelectAndFocusOnLogItemAtIndex.
float IngameDebugConsole.DebugLogRecycledListView._1OverLogItemHeight
Referenced by IngameDebugConsole.DebugLogRecycledListView.Initialize, IngameDebugConsole.DebugLogRecycledListView.UpdateItemsInTheList.
float IngameDebugConsole.DebugLogRecycledListView.viewportHeight
Referenced by IngameDebugConsole.DebugLogRecycledListView.Awake, IngameDebugConsole.DebugLogRecycledListView.OnLogEntriesUpdated, IngameDebugConsole.DebugLogRecycledListView.OnViewportDimensionsChanged, IngameDebugConsole.DebugLogRecycledListView.SelectAndFocusOnLogItemAtIndex, IngameDebugConsole.DebugLogRecycledListView.UpdateItemsInTheList.
List<DebugLogEntry> IngameDebugConsole.DebugLogRecycledListView.collapsedLogEntries
Referenced by IngameDebugConsole.DebugLogRecycledListView.Initialize, IngameDebugConsole.DebugLogRecycledListView.OnLogItemClickedInternal, IngameDebugConsole.DebugLogRecycledListView.UpdateLogItemContentsBetweenIndices.
DebugLogIndexList IngameDebugConsole.DebugLogRecycledListView.indicesOfEntriesToShow
Referenced by IngameDebugConsole.DebugLogRecycledListView.Initialize, IngameDebugConsole.DebugLogRecycledListView.OnLogItemClickedInternal, IngameDebugConsole.DebugLogRecycledListView.UpdateItemsInTheList, IngameDebugConsole.DebugLogRecycledListView.UpdateLogItemContentsBetweenIndices.
int IngameDebugConsole.DebugLogRecycledListView.indexOfSelectedLogEntry
Referenced by IngameDebugConsole.DebugLogRecycledListView.ColorLogItem, IngameDebugConsole.DebugLogRecycledListView.CreateLogItemAtIndex, IngameDebugConsole.DebugLogRecycledListView.DeselectSelectedLogItem, IngameDebugConsole.DebugLogRecycledListView.OnLogItemClickedInternal, IngameDebugConsole.DebugLogRecycledListView.SelectAndFocusOnLogItemAtIndex, IngameDebugConsole.DebugLogRecycledListView.UpdateLogItemContentsBetweenIndices.
float IngameDebugConsole.DebugLogRecycledListView.positionOfSelectedLogEntry
Referenced by IngameDebugConsole.DebugLogRecycledListView.DeselectSelectedLogItem, IngameDebugConsole.DebugLogRecycledListView.OnLogItemClickedInternal, IngameDebugConsole.DebugLogRecycledListView.UpdateItemsInTheList.
float IngameDebugConsole.DebugLogRecycledListView.heightOfSelectedLogEntry
Referenced by IngameDebugConsole.DebugLogRecycledListView.DeselectSelectedLogItem, IngameDebugConsole.DebugLogRecycledListView.OnLogItemClickedInternal.
float IngameDebugConsole.DebugLogRecycledListView.deltaHeightOfSelectedLogEntry
Referenced by IngameDebugConsole.DebugLogRecycledListView.CalculateContentHeight, IngameDebugConsole.DebugLogRecycledListView.CreateLogItemAtIndex, IngameDebugConsole.DebugLogRecycledListView.DeselectSelectedLogItem, IngameDebugConsole.DebugLogRecycledListView.OnLogItemClickedInternal, IngameDebugConsole.DebugLogRecycledListView.UpdateItemsInTheList.
Dictionary<int, DebugLogItem> IngameDebugConsole.DebugLogRecycledListView.logItemsAtIndices
Referenced by IngameDebugConsole.DebugLogRecycledListView.CreateLogItemAtIndex, IngameDebugConsole.DebugLogRecycledListView.DeselectSelectedLogItem, IngameDebugConsole.DebugLogRecycledListView.DestroyLogItemsBetweenIndices, IngameDebugConsole.DebugLogRecycledListView.OnCollapsedLogEntryAtIndexUpdated, IngameDebugConsole.DebugLogRecycledListView.OnLogItemClickedInternal, IngameDebugConsole.DebugLogRecycledListView.UpdateLogItemContentsBetweenIndices.
bool IngameDebugConsole.DebugLogRecycledListView.isCollapseOn
Referenced by IngameDebugConsole.DebugLogRecycledListView.SetCollapseMode, IngameDebugConsole.DebugLogRecycledListView.UpdateLogItemContentsBetweenIndices.
int IngameDebugConsole.DebugLogRecycledListView.currentTopIndex
Referenced by IngameDebugConsole.DebugLogRecycledListView.DeselectSelectedLogItem, IngameDebugConsole.DebugLogRecycledListView.HardResetItems, IngameDebugConsole.DebugLogRecycledListView.OnLogItemClickedInternal, IngameDebugConsole.DebugLogRecycledListView.UpdateItemsInTheList.
int IngameDebugConsole.DebugLogRecycledListView.currentBottomIndex
Referenced by IngameDebugConsole.DebugLogRecycledListView.DeselectSelectedLogItem, IngameDebugConsole.DebugLogRecycledListView.HardResetItems, IngameDebugConsole.DebugLogRecycledListView.OnLogItemClickedInternal, IngameDebugConsole.DebugLogRecycledListView.UpdateItemsInTheList.
float IngameDebugConsole.DebugLogRecycledListView.ItemHeight
float IngameDebugConsole.DebugLogRecycledListView.SelectedItemHeight
void IngameDebugConsole.DebugLogRecycledListView.Awake()
References IngameDebugConsole.DebugLogRecycledListView.scrollView, IngameDebugConsole.DebugLogRecycledListView.UpdateItemsInTheList, IngameDebugConsole.DebugLogRecycledListView.viewportHeight.
void IngameDebugConsole.DebugLogRecycledListView.OnLogItemClickedInternal(int itemIndex, DebugLogItem referenceItem=null)
References IngameDebugConsole.DebugLogRecycledListView.CalculateContentHeight, IngameDebugConsole.DebugLogRecycledListView.collapsedLogEntries, IngameDebugConsole.DebugLogRecycledListView.ColorLogItem, IngameDebugConsole.DebugLogRecycledListView.currentBottomIndex, IngameDebugConsole.DebugLogRecycledListView.currentTopIndex, IngameDebugConsole.DebugLogRecycledListView.deltaHeightOfSelectedLogEntry, IngameDebugConsole.DebugLogRecycledListView.DeselectSelectedLogItem, IngameDebugConsole.DebugLogRecycledListView.HardResetItems, IngameDebugConsole.DebugLogRecycledListView.heightOfSelectedLogEntry, IngameDebugConsole.DebugLogRecycledListView.indexOfSelectedLogEntry, IngameDebugConsole.DebugLogRecycledListView.indicesOfEntriesToShow, IngameDebugConsole.DebugLogRecycledListView.logItemHeight, IngameDebugConsole.DebugLogRecycledListView.logItemsAtIndices, IngameDebugConsole.DebugLogRecycledListView.positionOfSelectedLogEntry, IngameDebugConsole.DebugLogRecycledListView.UpdateItemsInTheList.
Referenced by IngameDebugConsole.DebugLogRecycledListView.OnLogItemClicked, IngameDebugConsole.DebugLogRecycledListView.SelectAndFocusOnLogItemAtIndex.
void IngameDebugConsole.DebugLogRecycledListView.HardResetItems()
References IngameDebugConsole.DebugLogRecycledListView.currentBottomIndex, IngameDebugConsole.DebugLogRecycledListView.currentTopIndex, IngameDebugConsole.DebugLogRecycledListView.DestroyLogItemsBetweenIndices.
Referenced by IngameDebugConsole.DebugLogRecycledListView.OnLogEntriesUpdated, IngameDebugConsole.DebugLogRecycledListView.OnLogItemClickedInternal, IngameDebugConsole.DebugLogRecycledListView.UpdateItemsInTheList.
void IngameDebugConsole.DebugLogRecycledListView.CalculateContentHeight()
References IngameDebugConsole.DebugLogRecycledListView.deltaHeightOfSelectedLogEntry, IngameDebugConsole.DebugLogRecycledListView.logItemHeight.
Referenced by IngameDebugConsole.DebugLogRecycledListView.OnLogEntriesUpdated, IngameDebugConsole.DebugLogRecycledListView.OnLogItemClickedInternal.
void IngameDebugConsole.DebugLogRecycledListView.CreateLogItemsBetweenIndices(int topIndex, int bottomIndex)
References IngameDebugConsole.DebugLogRecycledListView.CreateLogItemAtIndex.
Referenced by IngameDebugConsole.DebugLogRecycledListView.UpdateItemsInTheList.
void IngameDebugConsole.DebugLogRecycledListView.CreateLogItemAtIndex(int index)
References IngameDebugConsole.DebugLogRecycledListView.ColorLogItem, IngameDebugConsole.DebugLogRecycledListView.deltaHeightOfSelectedLogEntry, IngameDebugConsole.DebugLogRecycledListView.indexOfSelectedLogEntry, IngameDebugConsole.DebugLogRecycledListView.logItemHeight, IngameDebugConsole.DebugLogRecycledListView.logItemsAtIndices.
Referenced by IngameDebugConsole.DebugLogRecycledListView.CreateLogItemsBetweenIndices.
void IngameDebugConsole.DebugLogRecycledListView.DestroyLogItemsBetweenIndices(int topIndex, int bottomIndex)
References IngameDebugConsole.DebugLogRecycledListView.debugManager, IngameDebugConsole.DebugLogRecycledListView.logItemsAtIndices, IngameDebugConsole.DebugLogManager.PoolLogItem.
Referenced by IngameDebugConsole.DebugLogRecycledListView.HardResetItems, IngameDebugConsole.DebugLogRecycledListView.UpdateItemsInTheList.
void IngameDebugConsole.DebugLogRecycledListView.UpdateLogItemContentsBetweenIndices(int topIndex, int bottomIndex)
References IngameDebugConsole.DebugLogRecycledListView.collapsedLogEntries, IngameDebugConsole.DebugLogRecycledListView.indexOfSelectedLogEntry, IngameDebugConsole.DebugLogRecycledListView.indicesOfEntriesToShow, IngameDebugConsole.DebugLogRecycledListView.isCollapseOn, IngameDebugConsole.DebugLogRecycledListView.logItemsAtIndices.
Referenced by IngameDebugConsole.DebugLogRecycledListView.UpdateItemsInTheList.
void IngameDebugConsole.DebugLogRecycledListView.ColorLogItem(DebugLogItem logItem, int index)
References IngameDebugConsole.DebugLogRecycledListView.indexOfSelectedLogEntry, IngameDebugConsole.DebugLogRecycledListView.logItemNormalColor1, IngameDebugConsole.DebugLogRecycledListView.logItemNormalColor2, IngameDebugConsole.DebugLogRecycledListView.logItemSelectedColor.
Referenced by IngameDebugConsole.DebugLogRecycledListView.CreateLogItemAtIndex, IngameDebugConsole.DebugLogRecycledListView.DeselectSelectedLogItem, IngameDebugConsole.DebugLogRecycledListView.OnLogItemClickedInternal.
void IngameDebugConsole.DebugLogRecycledListView.Initialize(DebugLogManager manager, List< DebugLogEntry > collapsedLogEntries, DebugLogIndexList indicesOfEntriesToShow, float logItemHeight)
References IngameDebugConsole.DebugLogRecycledListView._1OverLogItemHeight, IngameDebugConsole.DebugLogRecycledListView.collapsedLogEntries, IngameDebugConsole.DebugLogRecycledListView.indicesOfEntriesToShow, IngameDebugConsole.DebugLogRecycledListView.logItemHeight, IngameDebugConsole.DebugLogRecycledListView.manager.
void IngameDebugConsole.DebugLogRecycledListView.SetCollapseMode(bool collapse)
References IngameDebugConsole.DebugLogRecycledListView.isCollapseOn.
void IngameDebugConsole.DebugLogRecycledListView.OnLogItemClicked(DebugLogItem item)
References IngameDebugConsole.DebugLogItem.Index, IngameDebugConsole.DebugLogRecycledListView.OnLogItemClickedInternal.
void IngameDebugConsole.DebugLogRecycledListView.SelectAndFocusOnLogItemAtIndex(int itemIndex)
References IngameDebugConsole.DebugLogRecycledListView.indexOfSelectedLogEntry, IngameDebugConsole.DebugLogRecycledListView.logItemHeight, IngameDebugConsole.DebugLogRecycledListView.OnLogItemClickedInternal, IngameDebugConsole.DebugLogRecycledListView.viewportHeight.
void IngameDebugConsole.DebugLogRecycledListView.DeselectSelectedLogItem()
References IngameDebugConsole.DebugLogRecycledListView.ColorLogItem, IngameDebugConsole.DebugLogRecycledListView.currentBottomIndex, IngameDebugConsole.DebugLogRecycledListView.currentTopIndex, IngameDebugConsole.DebugLogRecycledListView.deltaHeightOfSelectedLogEntry, IngameDebugConsole.DebugLogRecycledListView.heightOfSelectedLogEntry, IngameDebugConsole.DebugLogRecycledListView.indexOfSelectedLogEntry, IngameDebugConsole.DebugLogRecycledListView.logItemsAtIndices, IngameDebugConsole.DebugLogRecycledListView.positionOfSelectedLogEntry.
Referenced by IngameDebugConsole.DebugLogRecycledListView.OnLogItemClickedInternal.
void IngameDebugConsole.DebugLogRecycledListView.OnLogEntriesUpdated(bool updateAllVisibleItemContents)
References IngameDebugConsole.DebugLogRecycledListView.CalculateContentHeight, IngameDebugConsole.DebugLogRecycledListView.HardResetItems, IngameDebugConsole.DebugLogRecycledListView.UpdateItemsInTheList, IngameDebugConsole.DebugLogRecycledListView.viewportHeight.
void IngameDebugConsole.DebugLogRecycledListView.OnCollapsedLogEntryAtIndexUpdated(int index)
References IngameDebugConsole.DebugLogRecycledListView.logItemsAtIndices, IngameDebugConsole.DebugLogItem.ShowCount.
void IngameDebugConsole.DebugLogRecycledListView.OnViewportDimensionsChanged()
References IngameDebugConsole.DebugLogRecycledListView.UpdateItemsInTheList, IngameDebugConsole.DebugLogRecycledListView.viewportHeight.
void IngameDebugConsole.DebugLogRecycledListView.UpdateItemsInTheList(bool updateAllVisibleItemContents)
References IngameDebugConsole.DebugLogRecycledListView._1OverLogItemHeight, IngameDebugConsole.DebugLogIndexList.Count, IngameDebugConsole.DebugLogRecycledListView.CreateLogItemsBetweenIndices, IngameDebugConsole.DebugLogRecycledListView.currentBottomIndex, IngameDebugConsole.DebugLogRecycledListView.currentTopIndex, IngameDebugConsole.DebugLogRecycledListView.deltaHeightOfSelectedLogEntry, IngameDebugConsole.DebugLogRecycledListView.DestroyLogItemsBetweenIndices, IngameDebugConsole.DebugLogRecycledListView.HardResetItems, IngameDebugConsole.DebugLogRecycledListView.indicesOfEntriesToShow, IngameDebugConsole.DebugLogRecycledListView.positionOfSelectedLogEntry, IngameDebugConsole.DebugLogRecycledListView.UpdateLogItemContentsBetweenIndices, IngameDebugConsole.DebugLogRecycledListView.viewportHeight.
Referenced by IngameDebugConsole.DebugLogRecycledListView.Awake, IngameDebugConsole.DebugLogRecycledListView.OnLogEntriesUpdated, IngameDebugConsole.DebugLogRecycledListView.OnLogItemClickedInternal, IngameDebugConsole.DebugLogRecycledListView.OnViewportDimensionsChanged.